# 1. Week 6 → Week 7 transition

## 1.1 Week 6 starting point

Week 6 focused on improving the HealthConnect Clinic appointment no-show prediction model through error analysis, feature refinement, model comparison, and cross-validation.

The main Week 6 output was a refined Logistic Regression model selected as the final candidate model for progression into Week 7.

The selected model used the refined feature set developed from the Week 6 error analysis and validated Data Analytics findings. The feature set included patient, appointment, booking lead-time, previous no-show, distance, and interaction-related variables.

The Week 6 refined Logistic Regression model achieved the following test-set performance:

* Accuracy: 61.50%
* Precision: 60.87%
* Recall: 69.28%
* F1 Score: 64.80%
* ROC-AUC: 66.47%

Five-fold stratified cross-validation produced:

* Accuracy: 61.87%
* Precision: 62.47%
* Recall: 63.72%
* F1 Score: 63.09%
* ROC-AUC: 67.45%

The Refined Logistic Regression model was therefore carried forward as the Week 7 candidate model.

## 1.2 Main Week 6 limitation

Although the refined model showed a small improvement over the Week 5 baseline, its overall predictive performance remained moderate.

The Week 6 analysis also showed that false positives and false negatives remained present across important booking and patient segments. This indicated that further testing was required before considering the model suitable for wider use.

The Week 6 cross-track analysis also identified important relationships between booking lead time and previous no-shows. These findings provide a relevant dependency between the Data Science and Data Analytics tracks that can be validated during Week 7.

## 1.3 Component to be tested

The main component being tested in Week 7 is the Week 6 Refined Logistic Regression no-show prediction model.

Its intended purpose is to predict whether a HealthConnect Clinic appointment is likely to result in a no-show, using information available from the existing appointment data.

The Week 7 testing will therefore focus on whether the candidate model:

* produces consistent predictions;
* performs adequately on the test data;
* handles false positives and false negatives appropriately;
* performs consistently across important segments;
* generalises reasonably based on cross-validation results; and
* provides evidence that supports or challenges its intended use.

## 1.4 Connected tracks

The main cross-track dependency for Week 7 testing is Data Analytics, particularly the validated findings concerning booking lead time, previous no-shows, and their interaction.

Where relevant, model requirements and testing results will also be communicated to the ML Engineering track to support later implementation and integration.

## 1.5 Week 7 focus

Week 7 will not repeat the complete Week 5 or Week 6 analysis.

Instead, the existing Week 6 candidate will be tested systematically, weaknesses will be identified from the testing evidence, and targeted improvements will be made only where justified.

The Week 7 workflow will follow:

Test → Identify Issues → Refine → Re-test → Validate → Document

# 2. Week 7 testing readiness

## 2.1 Testing objective

The primary objective of Week 7 testing is to determine whether the Week 6 Refined Logistic Regression model performs consistently and reliably enough for its intended HealthConnect Clinic no-show prediction purpose.

The testing will specifically determine:

1. whether the candidate model reproduces its expected performance;
2. whether important false-positive and false-negative patterns remain;
3. whether performance weaknesses are concentrated in specific appointment or patient segments;
4. whether the model shows evidence of overfitting or poor generalisation;
5. whether the features supported by the Data Analytics findings contribute meaningfully to the candidate model;
6. whether any identified weaknesses justify a targeted refinement; and
7. whether the refined model demonstrates an improvement after re-testing.

## 2.2 Testing criteria

The following criteria will be used to evaluate the Week 6 candidate:

* Performance consistency: Test-set performance should be reasonably consistent with the Week 6 cross-validation results.
* Classification performance: Accuracy, precision, recall, F1 score, and ROC-AUC will be evaluated.
* Error behaviour: False positives and false negatives will be examined to identify important persistent patterns.
* Segment performance: Relevant segments will be tested where Week 6 or Data Analytics identified meaningful differences.
* Generalisation: Test-set and cross-validation performance will be compared to identify possible overfitting or instability.
* Feature support: Features introduced or retained during Week 6 will be assessed in relation to the testing findings.
* Improvement requirement: Any model refinement must be supported by evidence from testing rather than being introduced simply to increase a metric.
* Retesting: Any change made to the candidate model must be evaluated again using the same relevant performance measures.

## 2.3 Planned testing scenarios

| Test   | Scenario                                                                              | Expected result                                                                                            | Actual result                   | Status  |
| ------ | ------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------- | ------------------------------- | ------- |
| Test 1 | Re-evaluate the Week 6 candidate model on the existing test set                       | Performance should be consistent with the documented Week 6 candidate results                              | To be recorded after testing    | Pending |
| Test 2 | Evaluate classification metrics                                                       | Accuracy, precision, recall, F1 and ROC-AUC should be calculated successfully                              | To be recorded after testing    | Pending |
| Test 3 | Examine the confusion matrix                                                          | FP and FN behaviour should be identifiable and interpretable                                               | To be recorded after testing    | Pending |
| Test 4 | Test important error segments                                                         | Segment-level weaknesses should be identified where they exist                                             | To be recorded after testing    | Pending |
| Test 5 | Compare test performance with 5-fold cross-validation                                 | Large unexplained differences should be investigated as potential instability                              | To be recorded after testing    | Pending |
| Test 6 | Review the contribution of the refined feature set                                    | Features retained from Week 6 should have an evidence-based justification                                  | To be recorded after testing    | Pending |
| Test 7 | Test the Data Analytics-supported booking lead-time and previous no-show relationship | The model's behaviour should be consistent with validated analytical findings where applicable             | To be recorded after testing    | Pending |
| Test 8 | Re-test after any justified refinement                                                | The revised model should show either meaningful improvement or evidence supporting the refinement decision | To be recorded after refinement | Pending |

## 2.4 Testing evidence

The Week 7 notebook will maintain evidence for each testing activity.

Evidence will include, where applicable:

* model evaluation metrics;
* confusion matrices;
* error-analysis tables;
* segment-level testing results;
* comparison tables;
* cross-validation results;
* model refinement code;
* before-and-after results;
* cross-track validation evidence;
* testing decisions and interpretations; and
* final model suitability assessment.

The purpose of recording this evidence is to demonstrate that Week 7 progress is based on actual testing results rather than simply describing the Week 6 model.

## 2.5 Testing decision rule

A model change will only be made when the testing evidence identifies a meaningful weakness that can reasonably be addressed through refinement.

If a test does not identify a problem, the result will be documented as a successful validation rather than creating an artificial issue.


# 3. Re-establish the Week 6 candidate model

## 3.1 Week 6 candidate model

The Week 6 Refined Logistic Regression model is carried forward as the starting candidate for Week 7 testing.

The purpose of this step is to reproduce the existing Week 6 modelling setup sufficiently to allow systematic testing in the Week 7 notebook. This is not a new modelling exercise and does not repeat the complete Week 5 or Week 6 development process.

The Week 6 candidate will be evaluated using the same target definition, refined feature set and modelling approach used during Week 6.

The candidate model will serve as the reference point for:

* Week 7 performance testing;
* error and confusion-matrix testing;
* segment-level testing;
* generalisation testing;
* identification of weaknesses;
* evidence-based refinement; and
* subsequent re-testing.

## 3.2 Week 6 target definition

The prediction target remains no_show, where:

* 1 represents a No-Show appointment.
* 0 represents an Attended appointment.

Cancelled appointments were excluded from the modelling dataset during the earlier project stages.

## 3.3 Week 6 refined feature set

The Week 6 candidate model used the following refined features:

* gender
* age
* age_group
* appointment_type
* appointment_day
* booking_lead_days
* booking_lead_group
* previous_appointments
* previous_no_shows
* previous_no_show_group
* distance_to_clinic_km
* distance_group
* lead_no_show_interaction

These features are carried forward unchanged at this stage.

No additional feature engineering will be performed during this step.

## 3.4 Re-establishment principle

The Week 6 candidate model is being re-established only so that its behaviour can be tested in Week 7.

The Week 6 results will be treated as the reference results against which the Week 7 testing results are compared.

Any change to the model will only be introduced after a specific weakness has been identified through testing and supported by evidence.


## 3.5 Re-establish the Week 6 feature set

In [12]:
# Loading the Week 6 processed dataset

import pandas as pd
import numpy as np

df = pd.read_csv("HealthConnect_Processed_Dataset.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (4737, 15)


,gender,age,age_group,appointment_type,booking_date,appointment_date,appointment_day,appointment_time,booking_lead_days,previous_appointments,previous_no_shows,distance_to_clinic_km,booking_lead_group,distance_group,no_show
0,Female,39,35-44,Follow-up,2/6/2025,2/18/2025,Tuesday,Afternoon,12,2,0,19.3,8–14 days,16–20 km,1
1,Male,31,25-34,Specialist Consultation,2/25/2026,2/27/2026,Friday,Morning,2,6,0,14.3,0–7 days,11–15 km,0
2,Female,50,45-54,General Consultation,11/16/2025,12/24/2025,Wednesday,Morning,38,5,1,11.4,31–45 days,11–15 km,1
3,Male,59,55-64,Follow-up,7/18/2025,8/28/2025,Thursday,Evening,41,3,1,7.4,31–45 days,6–10 km,0
4,Female,34,25-34,Follow-up,7/9/2025,8/25/2025,Monday,Afternoon,47,3,1,5.6,46–60 days,6–10 km,1


In [13]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

df.columns.tolist()

Number of rows: 4737
Number of columns: 15


['gender',
 'age',
 'age_group',
 'appointment_type',
 'booking_date',
 'appointment_date',
 'appointment_day',
 'appointment_time',
 'booking_lead_days',
 'previous_appointments',
 'previous_no_shows',
 'distance_to_clinic_km',
 'booking_lead_group',
 'distance_group',
 'no_show']

In [14]:
df["no_show"].value_counts()

no_show
1    2423
0    2314
Name: count, dtype: int64

In [21]:
# Recreating the Week 6 engineered feature: previous no-show group

df["previous_no_show_group"] = np.where(df["previous_no_shows"] >= 3,"3+", df["previous_no_shows"].astype(str))

# Recreating the Week 6 interaction feature:
# booking lead-time group × previous no-show group

df["lead_no_show_interaction"] = (df["booking_lead_group"] + " | " + df["previous_no_show_group"]
)

# Checking the newly recreated features

print("previous_no_show_group:")
print(df["previous_no_show_group"].value_counts().sort_index())

print("\nlead_no_show_interaction:")
print(df["lead_no_show_interaction"].value_counts().sort_index())

previous_no_show_group:
previous_no_show_group
0     2745
1     1482
2      419
3+      91
Name: count, dtype: int64

lead_no_show_interaction:
lead_no_show_interaction
0–7 days | 0       355
0–7 days | 1       177
0–7 days | 2        59
0–7 days | 3+       13
15–30 days | 0     713
15–30 days | 1     405
15–30 days | 2     121
15–30 days | 3+     26
31–45 days | 0     691
31–45 days | 1     391
31–45 days | 2      86
31–45 days | 3+     19
46–60 days | 0     626
46–60 days | 1     361
46–60 days | 2      97
46–60 days | 3+     23
8–14 days | 0      360
8–14 days | 1      148
8–14 days | 2       56
8–14 days | 3+      10
Name: count, dtype: int64


In [26]:
# Week 6 refined feature set

refined_features = ['gender','age','age_group','appointment_type','appointment_day',
                    'booking_lead_days','booking_lead_group','previous_appointments',
                    'previous_no_shows','previous_no_show_group','distance_to_clinic_km',
                    'distance_group','lead_no_show_interaction']

refined_features

['gender',
 'age',
 'age_group',
 'appointment_type',
 'appointment_day',
 'booking_lead_days',
 'booking_lead_group',
 'previous_appointments',
 'previous_no_shows',
 'previous_no_show_group',
 'distance_to_clinic_km',
 'distance_group',
 'lead_no_show_interaction']

In [27]:
# Defining the numerical and categorical features

refined_numerical_features = ['age','booking_lead_days','previous_appointments',
                              'previous_no_shows','distance_to_clinic_km']

refined_categorical_features = ['gender','age_group','appointment_type','appointment_day',
                                'booking_lead_group','distance_group','previous_no_show_group',
                                'lead_no_show_interaction']

print("Numerical features:", refined_numerical_features)
print("Categorical features:", refined_categorical_features)

Numerical features: ['age', 'booking_lead_days', 'previous_appointments', 'previous_no_shows', 'distance_to_clinic_km']
Categorical features: ['gender', 'age_group', 'appointment_type', 'appointment_day', 'booking_lead_group', 'distance_group', 'previous_no_show_group', 'lead_no_show_interaction']


In [28]:
# Verifying the refined feature lists

print("Total refined features:", len(refined_features))
print("Total numerical features:", len(refined_numerical_features))
print("Total categorical features:", len(refined_categorical_features))

print("\nAll features accounted for:",
      len(refined_numerical_features) + len(refined_categorical_features) == len(refined_features))

Total refined features: 13
Total numerical features: 5
Total categorical features: 8

All features accounted for: True


In [29]:
# Creating the refined feature matrix and target

X_refined = df[refined_features].copy()
y_refined = df["no_show"].copy()

print("X_refined shape:", X_refined.shape)
print("y_refined shape:", y_refined.shape)

X_refined shape: (4737, 13)
y_refined shape: (4737,)


In [30]:
# Checking the missing values in refined features

X_refined.isnull().sum()

gender                      0
age                         0
age_group                   0
appointment_type            0
appointment_day             0
booking_lead_days           0
booking_lead_group          0
previous_appointments       0
previous_no_shows           0
previous_no_show_group      0
distance_to_clinic_km       0
distance_group              0
lead_no_show_interaction    0
dtype: int64

In [31]:
# Reviewing the refined categorical feature distributions

for column in refined_categorical_features:
    print(f"\n--- {column} ---")
    print(X_refined[column].value_counts())


--- gender ---
gender
Female               2358
Male                 2274
Prefer not to say     105
Name: count, dtype: int64

--- age_group ---
age_group
65+      1165
35-44     770
55-64     766
25-34     750
45-54     746
18-24     540
Name: count, dtype: int64

--- appointment_type ---
appointment_type
General Consultation       1980
Follow-up                  1344
Specialist Consultation     846
Diagnostic Test             567
Name: count, dtype: int64

--- appointment_day ---
appointment_day
Sunday       704
Friday       696
Wednesday    693
Saturday     683
Tuesday      662
Monday       655
Thursday     644
Name: count, dtype: int64

--- booking_lead_group ---
booking_lead_group
15–30 days    1265
31–45 days    1187
46–60 days    1107
0–7 days       604
8–14 days      574
Name: count, dtype: int64

--- distance_group ---
distance_group
6–10 km     1681
0–5 km      1103
11–15 km    1069
16–20 km     509
21–30 km     305
31–50 km      70
Name: count, dtype: int64

--- previous_no

## 3.6 Re-establish the Week 6 train-test split

In [82]:
from sklearn.model_selection import train_test_split
X_train_refined, X_test_refined, y_train_refined, y_test_refined = train_test_split(X_refined,y_refined,
                                                                                    test_size=0.20,
                                                                                    random_state=42,
                                                                                    stratify=y_refined)

print("X_train_refined:", X_train_refined.shape)
print("X_test_refined:", X_test_refined.shape)
print("y_train_refined:", y_train_refined.shape)
print("y_test_refined:", y_test_refined.shape)

X_train_refined: (3789, 13)
X_test_refined: (948, 13)
y_train_refined: (3789,)
y_test_refined: (948,)


In [86]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [34]:
# Creating the refined preprocessing pipeline

refined_preprocessor = ColumnTransformer(transformers=[("num", StandardScaler(), refined_numerical_features),
                                                       ("cat", OneHotEncoder(handle_unknown="ignore"), refined_categorical_features) ]
)

refined_preprocessor

,"transformers transformers: list of tuplesList of (name, transformer, columns) tuples specifying thetransformer objects to be applied to subsets of the data.name : str Like in Pipeline and FeatureUnion, this allows the transformer and its parameters to be set using ``set_params`` and searched in grid search.transformer : {'drop', 'passthrough'} or estimator Estimator must support :term:`fit` and :term:`transform`. Special-cased strings 'drop' and 'passthrough' are accepted as well, to indicate to drop the columns or to pass them through untransformed, respectively.columns : str, array-like of str, int, array-like of int, array-like of bool, slice or callable Indexes the data on its second axis. Integers are interpreted as positional columns, while strings can reference DataFrame columns by name. A scalar string or int should be used where ``transformer`` expects X to be a 1d array-like (vector), otherwise a 2d array will be passed to the transformer. A callable is passed the input data `X` and can return any of the above. To select multiple columns by name or dtype, you can use :obj:`make_column_selector`.","[('num', ...), ('cat', ...)]"
,"remainder remainder: {'drop', 'passthrough'} or estimator, default='drop'By default, only the specified columns in `transformers` aretransformed and combined in the output, and the non-specifiedcolumns are dropped. (default of ``'drop'``).By specifying ``remainder='passthrough'``, all remaining columns thatwere not specified in `transformers`, but present in the data passedto `fit` will be automatically passed through. This subset of columnsis concatenated with the output of the transformers. For dataframes,extra columns not seen during `fit` will be excluded from the outputof `transform`.By setting ``remainder`` to be an estimator, the remainingnon-specified columns will use the ``remainder`` estimator. Theestimator must support :term:`fit` and :term:`transform`.Note that using this feature requires that the DataFrame columnsinput at :term:`fit` and :term:`transform` have identical order.",'drop'
,"sparse_threshold sparse_threshold: float, default=0.3If the output of the different transformers contains sparse matrices,these will be stacked as a sparse matrix if the overall density islower than this value. Use ``sparse_threshold=0`` to always returndense. When the transformed output consists of all dense data, thestacked result will be dense, and this keyword will be ignored.",0.3
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.",None
,"transformer_weights transformer_weights: dict, default=NoneMultiplicative weights for features per transformer. The output of thetransformer is multiplied by these weights. Keys are transformer names,values the weights.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each transformer will beprinted as it is completed.",False
,"verbose_feature_names_out verbose_feature_names_out: bool, str or Callable[[str, str], str], default=True- If True, :meth:`ColumnTransformer.get_feature_names_out` will prefix all feature names with the name of the transformer that generated that feature. It is equivalent to setting `verbose_feature_names_out=""{transformer_name}__{feature_name}""`.- If False, :meth:`ColumnTransformer.get_feature_names_out` will not prefix any feature names and will error if feature names are not unique.- If ``Callable[[str, str], str]``, :meth:`ColumnTransformer.get_feature_names_out` will rename all the features using the name of the transformer. The first argument of the callable is the transformer name and the second argument is the feature name. The returned string will be the new feature name.- If ``str``, it must be a string ready for formatting. The given string will be formatted using two field names: ``transformer_name`` and ``feature_name``

## 3.7 Re-establish the Week 6 Logistic Regression Pipeline

In [87]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [35]:
refined_logistic_model = Pipeline(steps=[("preprocessor", refined_preprocessor),
                                         ("classifier", LogisticRegression(max_iter=1000,random_state=42 ))])

refined_logistic_model

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('preprocessor', ...), ('classifier', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"transformers transformers: list of tuplesList of (name, transformer, columns) tuples specifying thetransformer objects to be applied to subsets of the data.name : str Like in Pipeline and FeatureUnion, this allows the transformer and its parameters to be set using ``set_params`` and searched in grid search.transformer : {'drop', 'passthrough'} or estimator Estimator must support :term:`fit` and :term:`transform`. Special-cased strings 'drop' and 'passthrough' are accepted as well, to indicate to drop the columns or to pass them through untransformed, respectively.columns : str, array-like of str, int, array-like of int, array-like of bool, slice or callable Indexes the data on its second axis. Integers are interpreted as positional columns, while strings can reference DataFrame columns by name. A scalar string or int should be used where ``transformer`` expects X to be a 1d array-like (vector), otherwise a 2d array will be passed to the transformer. A callable is passed the input data `X` and can return any of the above. To select multiple columns by name or dtype, you can use :obj:`make_column_selector`.","[('num', ...), ('cat', ...)]"
,"remainder remainder: {'drop', 'passthrough'} or estimator, default='drop'By default, only the specified columns in `transformers` aretransformed and combined in the output, and the non-specifiedcolumns are dropped. (default of ``'drop'``).By specifying ``remainder='passthrough'``, all remaining columns thatwere not specified in `transformers`, but present in the data passedto `fit` will be automatically passed through. This subset of columnsis concatenated with the output of the transformers. For dataframes,extra columns not seen during `fit` will be excluded from the outputof `transform`.By setting ``remainder`` to be an estimator, the remainingnon-specified columns will use the ``remainder`` estimator. Theestimator must support :term:`fit` and :term:`transform`.Note that using this feature requires that the DataFrame columnsinput at :term:`fit` and :term:`transform` have identical order.",'drop'
,"sparse_threshold sparse_threshold: float, default=0.3I

## 3.8 Train refined Logistic Regression model

In [36]:
refined_logistic_model.fit(X_train_refined,y_train_refined)

print("Refined Logistic Regression model trained successfully.")

Refined Logistic Regression model trained successfully.


## 3.9 Generating predictions from the refined model

In [38]:
y_pred_refined = refined_logistic_model.predict(X_test_refined)
y_prob_refined = refined_logistic_model.predict_proba(X_test_refined)[:, 1]

print("Predictions generated:", len(y_pred_refined))
print("Probability predictions generated:", len(y_prob_refined))

Predictions generated: 948
Probability predictions generated: 948


# 4. Candidate model testing: Classification metrics

In [40]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

# Calculate classification metrics for the Week 6 candidate model

accuracy = accuracy_score(y_test_refined, y_pred_refined)
precision = precision_score(y_test_refined, y_pred_refined)
recall = recall_score(y_test_refined, y_pred_refined)
f1 = f1_score(y_test_refined, y_pred_refined)
roc_auc = roc_auc_score(y_test_refined, y_prob_refined)

print("Week 7 Candidate model results")
print("--------------------------------")
print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1 Score:  {f1:.4f}")
print(f"ROC-AUC:   {roc_auc:.4f}")

Week 7 Candidate model results
--------------------------------
Accuracy:  0.6150
Precision: 0.6087
Recall:    0.6928
F1 Score:  0.6480
ROC-AUC:   0.6647


### 4.1 Prediction validation

The Week 6 Refined Logistic Regression candidate was successfully re-established in the Week 7 notebook using the same refined feature set, preprocessing pipeline, train-test split (test_size=0.20, random_state=42, stratified target), and Logistic Regression configuration.

The model generated predictions for all 948 observations in the Week 7 test set, confirming that the candidate model could be reproduced successfully.

Testing Result: Pass

No reproduction issue was identified.

### 4.2 Classification metrics

The Week 7 candidate model produced exactly the same classification metrics as the Week 6 Refined Logistic Regression model:

- Accuracy: 61.50%
- Precision: 60.87%
- Recall: 69.28%
- F1 Score: 64.80%
- ROC-AUC: 66.47%

The identical results confirm that the Week 6 candidate model has been consistently reproduced in the Week 7 testing environment.

Testing Result: Pass

In [41]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test_refined, y_pred_refined)

print("Confusion matrix:")
print(cm)

Confusion matrix:
[[247 216]
 [149 336]]


### 4.3 Confusion matrix validation

The confusion matrix for the reproduced Week 6 refined Logistic Regression model was:

```text
[[247 216]
 [149 336]]
```

The matrix was interpreted using 0 = Attended and 1 = No-Show:

* True Negatives (TN): 247
* False Positives (FP): 216
* False Negatives (FN): 149
* True Positives (TP): 336

The confusion matrix exactly matches the Week 6 refined Logistic Regression results. This confirms that the model's classification behaviour was successfully reproduced on the same test set.

Testing result: Pass

No reproduction issue was identified from the confusion matrix validation. The observed false-positive and false-negative patterns will be examined further during the dedicated error testing and segment performance testing stages.


In [88]:
roc_auc = roc_auc_score(y_test_refined, y_prob_refined)

print(f"ROC-AUC: {roc_auc:.4f}")

ROC-AUC: 0.6647


## 4.4 ROC-AUC

The ROC-AUC of the reproduced Week 6 refined Logistic Regression model was 0.6647.

This exactly matches the Week 6 ROC-AUC result of 0.6647. The result confirms that the model's probability-ranking behaviour was successfully reproduced during Week 7 testing.

Testing result: Pass

No reproduction discrepancy was identified in the ROC-AUC evaluation. The candidate model therefore passed the initial prediction, classification-metric, confusion-matrix, and ROC-AUC validation tests.


## 5.1 Error classification validation

The Week 6 candidate model produced false positives and false negatives that were examined during error analysis. In Week 7, these error categories are tested again using the reproduced test-set predictions.

The objective is to confirm that each test-set observation is consistently classified as a true negative, false positive, false negative, or true positive.

The error classification will then be used for the subsequent segment-level error testing.


In [48]:
# Creating an error-analysis dataset from the Week 7 test-set predictions

error_analysis = X_test_refined.copy()

error_analysis["actual"] = y_test_refined.values
error_analysis["predicted"] = y_pred_refined

error_analysis["prediction_result"] = np.select(
    [
        (error_analysis["actual"] == 0) & (error_analysis["predicted"] == 0),
        (error_analysis["actual"] == 0) & (error_analysis["predicted"] == 1),
        (error_analysis["actual"] == 1) & (error_analysis["predicted"] == 0),
        (error_analysis["actual"] == 1) & (error_analysis["predicted"] == 1)
    ],
    [
        "True Negative",
        "False Positive",
        "False Negative",
        "True Positive"
    ],
    default="Unknown"
)

error_analysis["prediction_result"].value_counts()

prediction_result
True Positive     336
True Negative     247
False Positive    216
False Negative    149
Name: count, dtype: int64

### Result - Error classification

The Week 7 candidate model reproduced the Week 6 error classification exactly. The test set contained 247 true negatives, 216 false positives, 149 false negatives, and 336 true positives, matching the Week 6 results.

Test status: Pass

This confirms that the reproduced candidate model generates the same classification outcomes as the Week 6 model. The analysis can therefore proceed to testing whether the previously identified false-positive and false-negative patterns remain consistent across important data segments.


## 5.2 Booking lead-time error pattern validation

In [49]:
# Testing whether the Week 6 error pattern by booking lead-time group is reproduced in the Week 7 candidate model

lead_error_test = pd.crosstab(error_analysis["booking_lead_group"],error_analysis["prediction_result"])

# Ensuring that all error categories are present and consistently ordered

lead_error_test = lead_error_test.reindex(columns=["True Negative","False Positive",
                                                   "False Negative","True Positive"
                                                  ],
                                          fill_value=0
)

# Calculating the total observations, total errors, and error rate

lead_error_test["Total"] = lead_error_test.sum(axis=1)

lead_error_test["Errors"] = (lead_error_test["False Positive"] + lead_error_test["False Negative"])

lead_error_test["Error Rate (%)"] = (lead_error_test["Errors"] / lead_error_test["Total"]* 100).round(2)

lead_error_test

prediction_result,True Negative,False Positive,False Negative,True Positive,Total,Errors,Error Rate (%)
booking_lead_group,,,,,,,
0–7 days,85,1,28,5,119,29,24.37
15–30 days,89,34,74,31,228,108,47.37
31–45 days,9,105,12,123,249,117,46.99
46–60 days,0,71,0,172,243,71,29.22
8–14 days,64,5,35,5,109,40,36.70


### Result - Booking lead-time error pattern

The Week 7 testing reproduced the main booking lead-time error pattern identified during Week 6. The 15–30 day and 31–45 day groups continued to show the highest error rates at 47.37% and 46.99%, respectively. The 8–14 day group showed a moderate error rate of 36.70%, while the 0–7 day and 46–60 day groups had lower error rates of 24.37% and 29.22%.

Although the individual error counts differed slightly from the Week 6 results, the relative pattern across booking lead-time groups remained consistent. This supports the Week 6 finding that booking lead time is an important source of prediction error.

Test status: Pass

The result does not indicate that the candidate model is error-free. Instead, it validates that the previously identified booking lead-time weaknesses remain present and should continue to be considered during subsequent testing and refinement.

## 5.3 Previous No-Show error pattern validation.

In [50]:
# Testing whether the Week 6 error pattern by previous no-shows is reproduced in the Week 7 candidate model

previous_no_show_error_test = pd.crosstab(error_analysis["previous_no_show_group"], error_analysis["prediction_result"])

# Ensuring that all error categories are present and consistently ordered

previous_no_show_error_test = previous_no_show_error_test.reindex(columns=["True Negative","False Positive",
                                                                           "False Negative","True Positive"
                                                                          ],
    fill_value=0
)

# Calculating the total observations, total errors, and error rate

previous_no_show_error_test["Total"] = (previous_no_show_error_test.sum(axis=1))

previous_no_show_error_test["Errors"] = (previous_no_show_error_test["False Positive"]+ previous_no_show_error_test["False Negative"])

previous_no_show_error_test["Error Rate (%)"] = (previous_no_show_error_test["Errors"] / previous_no_show_error_test["Total"]* 100).round(2)

previous_no_show_error_test

prediction_result,True Negative,False Positive,False Negative,True Positive,Total,Errors,Error Rate (%)
previous_no_show_group,,,,,,,
0,171,115,102,155,543,217,39.96
1,67,66,41,128,302,107,35.43
2,6,30,5,44,85,35,41.18
3+,3,5,1,9,18,6,33.33


### Result previous No-Show error pattern

The Week 7 candidate model was tested across the previous no-show groups to determine whether the error behaviour identified during Week 6 remained consistent.

The largest group, patients with 0 previous no-shows, had an error rate of 39.96%. The error rate was 35.43% for patients with 1 previous no-show and 41.18% for patients with 2 previous no-shows. The 3+ group had a lower error rate of 33.33%, but this group contained only 18 observations.

The results therefore show that prediction errors remain present across all previous no-show groups, with no clear evidence that the candidate model performs consistently better as previous no-shows increase. The 3+ result should be interpreted cautiously because of its small sample size.

Test status: Pass with caution

The main Week 6 error pattern is reproduced sufficiently for validation purposes. However, previous no-show history remains an important feature for subsequent testing because it is associated with different prediction behaviour across groups and forms part of the validated booking lead-time × previous no-show interaction.


## 5.4 Appointment type

In [51]:
# Testing whether the Week 6 error pattern by appointment type is reproduced in the Week 7 candidate model

appointment_type_error_test = pd.crosstab(error_analysis["appointment_type"], error_analysis["prediction_result"])

appointment_type_error_test = appointment_type_error_test.reindex(columns=["True Negative","False Positive",
                                                                           "False Negative","True Positive"
                                                                          ],
    fill_value=0
)

appointment_type_error_test["Total"] = (appointment_type_error_test.sum(axis=1))

appointment_type_error_test["Errors"] = (appointment_type_error_test["False Positive"]+ appointment_type_error_test["False Negative"])

appointment_type_error_test["Error Rate (%)"] = (appointment_type_error_test["Errors"]/ appointment_type_error_test["Total"]* 100).round(2)

appointment_type_error_test

prediction_result,True Negative,False Positive,False Negative,True Positive,Total,Errors,Error Rate (%)
appointment_type,,,,,,,
Diagnostic Test,21,32,18,44,115,50,43.48
Follow-up,67,56,46,110,279,102,36.56
General Consultation,116,86,59,134,395,145,36.71
Specialist Consultation,43,42,26,48,159,68,42.77


### Result appointment type error pattern

The Week 7 candidate model was tested across appointment types to determine whether the error pattern identified during Week 6 was reproduced.

Diagnostic Test appointments had the highest error rate at 43.48%, followed by Specialist Consultation at 42.77%. General Consultation and Follow-up appointments had lower error rates of 36.71% and 36.56%, respectively.

This result is broadly consistent with the Week 6 finding that Diagnostic Test and Specialist Consultation appointments showed higher prediction error, while General Consultation and Follow-up appointments had lower error rates. However, the differences between the groups are relatively small compared with the stronger error patterns observed for booking lead-time groups.

Test status: Pass

The appointment-type error pattern identified in Week 6 is sufficiently reproduced in Week 7. However, the results do not provide strong enough evidence to justify additional refinement based on appointment type alone.


## 5.5 Age group error pattern validation

In [53]:
# Testing whether the Week 6 error pattern by age group is reproduced in the Week 7 candidate model

age_error_test = pd.crosstab(error_analysis["age_group"],error_analysis["prediction_result"])

age_error_test = age_error_test.reindex(columns=["True Negative","False Positive",
                                                 "False Negative","True Positive"
                                                ],
    fill_value=0
)

age_error_test["Total"] = (age_error_test.sum(axis=1))

age_error_test["Errors"] = (age_error_test["False Positive"]+ age_error_test["False Negative"])

age_error_test["Error Rate (%)"] = (age_error_test["Errors"]/ age_error_test["Total"]* 100).round(2)

age_error_test

prediction_result,True Negative,False Positive,False Negative,True Positive,Total,Errors,Error Rate (%)
age_group,,,,,,,
18-24,31,21,21,42,115,42,36.52
25-34,34,34,16,52,136,50,36.76
35-44,36,34,30,56,156,64,41.03
45-54,37,35,26,50,148,61,41.22
55-64,35,38,22,73,168,60,35.71
65+,74,54,34,63,225,88,39.11


### Result age group error pattern

The Week 7 candidate model was tested across age groups to determine whether the error pattern identified during Week 6 was reproduced.

The 45–54 age group had the highest error rate at 41.22%, followed closely by the 35–44 group at 41.03%. The 65+ group had an error rate of 39.11%, while the 18–24 and 25–34 groups had error rates of 36.52% and 36.76%, respectively. The 55–64 group had the lowest error rate at 35.71%.

The results are broadly consistent with the Week 6 finding that prediction errors varied across age groups, with the middle-aged groups showing relatively higher error rates. However, the differences between the groups remain relatively modest, indicating that age group is not a dominant source of prediction error.

Test status: Pass

The Week 6 age-group error pattern is sufficiently reproduced in Week 7. The results do not provide strong evidence for additional refinement based on age group alone.


## 5.6 Appointment day error pattern validation

In [54]:
# Testing whether the Week 6 error pattern by appointment day is reproduced in the Week 7 candidate model

day_error_test = pd.crosstab(error_analysis["appointment_day"], error_analysis["prediction_result"])

day_error_test = day_error_test.reindex(columns=["True Negative","False Positive",
                                                 "False Negative","True Positive"
                                                ],
    fill_value=0
)

day_error_test["Total"] = (day_error_test.sum(axis=1))

day_error_test["Errors"] = (day_error_test["False Positive"]+ day_error_test["False Negative"])

day_error_test["Error Rate (%)"] = (day_error_test["Errors"]/ day_error_test["Total"]* 100).round(2)

day_error_test

prediction_result,True Negative,False Positive,False Negative,True Positive,Total,Errors,Error Rate (%)
appointment_day,,,,,,,
Friday,35,33,30,42,140,63,45.00
Monday,33,21,21,51,126,42,33.33
Saturday,39,24,22,45,130,46,35.38
Sunday,35,44,21,48,148,65,43.92
Thursday,31,25,21,42,119,46,38.66
Tuesday,42,31,15,44,132,46,34.85
Wednesday,32,38,19,64,153,57,37.25


### Result appointment day error pattern

The Week 7 candidate model was tested across appointment days to determine whether the error pattern identified during Week 6 was reproduced.

Friday had the highest error rate at 45.00%, followed by Sunday at 43.92%. Monday had the lowest error rate at 33.33%, while Tuesday and Saturday had error rates of 34.85% and 35.38%, respectively. Wednesday and Thursday had error rates of 37.25% and 38.66%.

The results are broadly consistent with the Week 6 finding that prediction errors varied across appointment days, with Friday and Sunday showing relatively higher error rates. However, the differences between the groups remain relatively modest.

Test status: Pass

The Week 6 appointment-day error pattern is sufficiently reproduced in Week 7. The results do not provide strong evidence that appointment day alone is a major source of prediction error or that additional refinement based solely on appointment day is required.


## 5.7 Appointment time error pattern validation.

In [58]:
# Adding the appointment_time from the original dataset to the test-set error analysis

error_analysis["appointment_time"] = df.loc[error_analysis.index, "appointment_time"]

# Testing whether the Week 6 error pattern by appointment time is reproduced in the Week 7 candidate model

time_error_test = pd.crosstab(error_analysis["appointment_time"],error_analysis["prediction_result"])

time_error_test = time_error_test.reindex(columns=["True Negative","False Positive",
                                                   "False Negative","True Positive"
                                                  ],
    fill_value=0
)

time_error_test["Total"] = time_error_test.sum(axis=1)

time_error_test["Errors"] = (time_error_test["False Positive"]+ time_error_test["False Negative"])

time_error_test["Error Rate (%)"] = (time_error_test["Errors"]/ time_error_test["Total"]* 100).round(2)

time_error_test

prediction_result,True Negative,False Positive,False Negative,True Positive,Total,Errors,Error Rate (%)
appointment_time,,,,,,,
Afternoon,99,84,59,140,382,143,37.43
Evening,33,32,22,62,149,54,36.24
Morning,115,100,68,134,417,168,40.29


### Result appointment time error pattern

The Week 7 candidate model was tested to determine whether the appointment-time error pattern observed during Week 6 remained consistent. Morning appointments had the highest error rate at 40.29%, followed by Afternoon appointments at 37.43% and Evening appointments at 36.24%. Although Morning appointments showed somewhat higher errors, the differences between the three groups were modest. Therefore, there is insufficient evidence that appointment time alone represents a strong model weakness requiring feature refinement.

Testing decision: Pass 

The appointment-time error pattern has been successfully validated. No refinement will be made based on appointment time alone.

## 5.8 Distance group error pattern validation.

In [60]:
# Testing whether the Week 6 error pattern by distance group is reproduced in the Week 7 candidate model

distance_error_test = pd.crosstab(error_analysis["distance_group"],error_analysis["prediction_result"])

distance_error_test = distance_error_test.reindex(columns=["True Negative","False Positive",
                                                           "False Negative","True Positive"
                                                          ],
    fill_value=0
)

distance_error_test["Total"] = distance_error_test.sum(axis=1)

distance_error_test["Errors"] = (distance_error_test["False Positive"]+ distance_error_test["False Negative"])

distance_error_test["Error Rate (%)"] = (distance_error_test["Errors"]/ distance_error_test["Total"] * 100).round(2)

distance_error_test

prediction_result,True Negative,False Positive,False Negative,True Positive,Total,Errors,Error Rate (%)
distance_group,,,,,,,
0–5 km,63,34,47,63,207,81,39.13
11–15 km,47,56,38,77,218,94,43.12
16–20 km,20,26,13,38,97,39,40.21
21–30 km,16,19,4,30,69,23,33.33
31–50 km,0,6,1,8,15,7,46.67
6–10 km,101,75,46,120,342,121,35.38


### Result distance group error pattern

The Week 7 candidate model was tested to determine whether the distance-related error patterns observed during Week 6 remained consistent after reproducing the candidate model.

The 31–50 km group recorded the highest error rate at 46.67%, followed by the 11–15 km group at 43.12% and the 16–20 km group at 40.21%. However, the 31–50 km group contained only 15 observations, so its relatively high error rate should be interpreted with caution.

The 6–10 km group had an error rate of 35.38%, while the 21–30 km group had the lowest error rate at 33.33%. Overall, the results do not show a clear monotonic relationship between distance and model error.

The Week 7 results are broadly consistent with the Week 6 findings, where some longer-distance groups showed higher error rates but the smallest distance group did not necessarily have the lowest error rate.

Testing decision: Pass

The distance-group error pattern has been successfully validated. Although some distance groups show higher error rates, there is insufficient evidence that distance group alone represents a sufficiently strong model weakness to justify feature refinement at this stage. The small sample size of the 31–50 km group should also be considered when interpreting this result.


### 5.9 Overall error testing conclusion

The Week 7 error testing successfully reproduced the major error patterns identified during Week 6 for the Refined Logistic Regression candidate model.

The model continued to produce both false positives and false negatives across all tested segments. The most notable error patterns were observed across booking lead-time groups, particularly the 15–30 day and 31–45 day groups. Previous no-show history also remained relevant, although the smaller 3+ previous no-show group requires caution because of its limited sample size.

Testing across appointment type, age, appointment day, appointment time and distance groups did not identify a sufficiently strong and consistent weakness that would independently justify immediate feature refinement. The distance analysis similarly showed variation between groups, but no clear monotonic error pattern. The 31–50 km group recorded a relatively high error rate, but its small sample size of 15 observations limits the strength of this finding.

Overall, the error-testing results support the reproducibility of the Week 6 error analysis while confirming that the candidate model still has areas requiring further validation.

Testing decision: Pass 

The Week 6 error patterns were successfully re-tested in Week 7. No unsupported feature changes will be made solely on the basis of these segment-level error rates. Further testing will focus on broader segment performance, model generalisation and whether the candidate model remains suitable for the intended HealthConnect use case.


# 6. Segment performance testing

In [67]:
lead_group_order = ["0–7 days","8–14 days","15–30 days","31–45 days","46–60 days"]

lead_performance = []

for group in lead_group_order:

    group_data = error_analysis[error_analysis["booking_lead_group"] == group]

    y_true_group = group_data["actual"]
    y_pred_group = group_data["predicted"]

    lead_performance.append({"Booking Lead Group": group,
                             "Total": len(group_data),
                             "Actual No-Show Rate (%)": round(y_true_group.mean() * 100, 2),
                             "Accuracy (%)": round(accuracy_score(y_true_group, y_pred_group) * 100, 2),
                             "Precision (%)": round(precision_score(y_true_group,y_pred_group,
                                                                    zero_division=0 ) * 100, 2),
                             "Recall (%)": round( recall_score(y_true_group,y_pred_group,
                                                               zero_division=0) * 100, 2),
                             "F1 Score (%)": round(f1_score(y_true_group,y_pred_group,
                                                            zero_division=0) * 100, 2) 
                            })

lead_performance = pd.DataFrame(lead_performance)

lead_performance

,Booking Lead Group,Total,Actual No-Show Rate (%),Accuracy (%),Precision (%),Recall (%),F1 Score (%)
0,0–7 days,119,27.73,75.63,83.33,15.15,25.64
1,8–14 days,109,36.70,63.30,50.00,12.50,20.00
2,15–30 days,228,46.05,52.63,47.69,29.52,36.47
3,31–45 days,249,54.22,53.01,53.95,91.11,67.77
4,46–60 days,243,70.78,70.78,70.78,100.00,82.89


### Interpretation

The Week 7 segment performance testing shows that the Refined Logistic Regression model performs differently across booking lead-time groups.

The 0–7 days group achieved an accuracy of 75.63%, but its recall was only 15.15%, indicating that the model identified relatively few of the actual no-show appointments in this segment. Similarly, the 8–14 days group recorded an accuracy of 63.30% but a low recall of 12.50%.

Performance was weaker in the 15–30 days group, which recorded 52.63% accuracy, 47.69% precision, 29.52% recall, and an F1-score of 36.47%. This indicates that the model has difficulty distinguishing attended and no-show appointments within this segment.

In contrast, model performance improved substantially for longer booking lead times. The 31–45 days group achieved 91.11% recall and an F1-score of 67.77%, while the 46–60 days group achieved 100.00% recall and an F1-score of 82.89%.

These results indicate that the model is considerably better at identifying no-shows among appointments booked further in advance than among appointments booked within shorter lead-time periods. This is consistent with the Week 6 Data Analytics findings, which identified booking lead time as an important behavioural pattern associated with appointment attendance.

The results therefore identify the shorter booking lead-time groups, particularly 0–7 days and 8–14 days, as areas requiring further validation. However, the findings alone do not justify an immediate feature change. Further segment testing and generalisation testing are required before deciding whether model refinement is necessary.

Testing decision: Pass with observation 

The booking lead-time segment performance test was successfully completed and identified a meaningful performance difference across segments. The finding will be carried forward for further testing before any additional model refinement is considered.


## 6.2 Previous No-Show history segment performance

In [69]:
previous_no_show_order = ["0","1","2","3+"]

previous_no_show_performance = []

for group in previous_no_show_order:

    group_data = error_analysis[error_analysis["previous_no_show_group"] == group]

    y_true_group = group_data["actual"]
    y_pred_group = group_data["predicted"]

    previous_no_show_performance.append({"Previous No-Show Group": group,
                                         "Total": len(group_data),
                                         "Actual No-Show Rate (%)": round(y_true_group.mean() * 100, 2),
                                         "Accuracy (%)": round(accuracy_score(y_true_group, y_pred_group) * 100, 2),
                                         "Precision (%)": round(precision_score(y_true_group,y_pred_group,
                                                                                zero_division=0) * 100, 2),
                                         "Recall (%)": round(recall_score(y_true_group,y_pred_group,
                                                                          zero_division=0) * 100, 2),
                                         "F1 Score (%)": round(f1_score(y_true_group,y_pred_group,
                                                                        zero_division=0) * 100, 2)
                                        })

previous_no_show_performance = pd.DataFrame(previous_no_show_performance)

previous_no_show_performance

,Previous No-Show Group,Total,Actual No-Show Rate (%),Accuracy (%),Precision (%),Recall (%),F1 Score (%)
0,0,543,47.33,60.04,57.41,60.31,58.82
1,1,302,55.96,64.57,65.98,75.74,70.52
2,2,85,57.65,58.82,59.46,89.80,71.54
3,3+,18,55.56,66.67,64.29,90.00,75.00


### Interpretation

The Week 7 segment performance testing shows that the Refined Logistic Regression model performs differently across groups based on patients' previous no-show history.

Patients with 0 previous no-shows recorded an actual no-show rate of 47.33%. The model achieved 60.04% accuracy, 57.41% precision, 60.31% recall, and an F1-score of 58.82% in this group.

For patients with 1 previous no-show, the actual no-show rate increased to 55.96%. Model performance also improved, with 64.57% accuracy, 65.98% precision, 75.74% recall, and an F1-score of 70.52%.

The 2 previous no-shows group had an actual no-show rate of 57.65%. The model achieved 58.82% accuracy, 59.46% precision, 89.80% recall, and an F1-score of 71.54%. Although accuracy was relatively low, the high recall indicates that the model identified most of the actual no-shows in this group.

The 3+ previous no-shows group recorded an actual no-show rate of 55.56% and achieved 66.67% accuracy, 64.29% precision, 90.00% recall, and an F1-score of 75.00%. However, this group contains only 18 observations, so the results should be interpreted cautiously and should not be treated as strong evidence of general model performance for patients with three or more previous no-shows.

Overall, the results indicate that previous no-show history remains an important segment for model performance. The model generally achieves higher recall among patients with previous no-shows than among patients with no previous no-shows. This supports the Week 6 Data Analytics finding that previous no-show history contains useful predictive information.

However, the results do not provide sufficient evidence to make an additional feature change at this stage. The small size of the `3+` group limits the reliability of its performance estimates, while the broader results should be considered together with the booking lead-time findings and subsequent generalisation testing.

Testing decision: Pass with observation 

The previous no-show history segment test was successfully completed. The results support the continued use of previous no-show history as a predictive feature, while the 3+ group requires cautious interpretation because of its small sample size. No additional refinement will be made based on this segment test alone.


## 6.3 Appointment type segment performance

In [72]:
appointment_type_order = ["Diagnostic Test","Follow-up","General Consultation","Specialist Consultation"]

appointment_type_performance = []

for group in appointment_type_order:

    group_data = error_analysis[error_analysis["appointment_type"] == group]

    y_true_group = group_data["actual"]
    y_pred_group = group_data["predicted"]

    appointment_type_performance.append({"Appointment Type": group,
                                         "Total": len(group_data),
                                         "Actual No-Show Rate (%)": round(y_true_group.mean() * 100, 2),
                                         "Accuracy (%)": round(accuracy_score(y_true_group,y_pred_group) * 100, 2),
                                         "Precision (%)": round(precision_score(y_true_group,y_pred_group,
                                                                                zero_division=0) * 100, 2),
                                         "Recall (%)": round(recall_score(y_true_group,y_pred_group,
                                                                          zero_division=0) * 100, 2),
                                         "F1 Score (%)": round(f1_score(y_true_group,y_pred_group,
                                                                        zero_division=0) * 100, 2)
                                        })

appointment_type_performance = pd.DataFrame(appointment_type_performance)

appointment_type_performance

,Appointment Type,Total,Actual No-Show Rate (%),Accuracy (%),Precision (%),Recall (%),F1 Score (%)
0,Diagnostic Test,115,53.91,56.52,57.89,70.97,63.77
1,Follow-up,279,55.91,63.44,66.27,70.51,68.32
2,General Consultation,395,48.86,63.29,60.91,69.43,64.89
3,Specialist Consultation,159,46.54,57.23,53.33,64.86,58.54


### Interpretation

The Week 7 segment performance testing shows that the Refined Logistic Regression model performs somewhat differently across appointment types.

The Diagnostic Test group achieved an accuracy of 56.52%, precision of 57.89%, recall of 70.97% and an F1-score of 63.77%. The relatively high recall indicates that the model identified a substantial proportion of the actual no-show appointments in this group.

The Follow-up group showed the strongest overall performance, with 63.44% accuracy, 66.27% precision, 70.51% recall and an F1-score of 68.32%. General Consultation produced similar accuracy at 63.29%, with an F1-score of 64.89%.

Specialist Consultation recorded the lowest accuracy at 57.23% and the lowest F1-score at 58.54%. This indicates somewhat weaker classification performance for this segment compared with the other appointment types.

Overall, the differences between appointment types are moderate and do not provide sufficiently strong evidence that appointment type alone is causing a major model weakness. The results therefore support continued use of appointment type as a model feature, but no additional feature refinement will be made based on appointment type performance alone.

Testing decision: Pass with observation 

Appointment-type segment performance was successfully validated. The Specialist Consultation and Diagnostic Test groups will remain areas for monitoring during subsequent validation, but no unsupported model changes will be introduced based on this test alone.

## 6.4 Age segment performance testing

In [75]:
age_group_order = [ "18-24","25-34","35-44","45-54","55-64","65+"]

age_performance = []

for group in age_group_order:

    group_data = error_analysis[error_analysis["age_group"] == group]

    y_true_group = group_data["actual"]
    y_pred_group = group_data["predicted"]

    age_performance.append({"Age Group": group,
                            "Total": len(group_data),
                            "Actual No-Show Rate (%)": round(y_true_group.mean() * 100, 2),
                            "Accuracy (%)": round(accuracy_score(y_true_group,y_pred_group) * 100, 2),
                            "Precision (%)": round(precision_score(y_true_group,y_pred_group,
                                                                   zero_division=0) * 100, 2),
                            "Recall (%)": round(recall_score(y_true_group,y_pred_group,
                                                             zero_division=0) * 100, 2),
                            "F1 Score (%)": round(f1_score(y_true_group,y_pred_group,
                                                           zero_division=0) * 100, 2)
                           })

age_performance = pd.DataFrame(age_performance)

age_performance

,Age Group,Total,Actual No-Show Rate (%),Accuracy (%),Precision (%),Recall (%),F1 Score (%)
0,18-24,115,54.78,63.48,66.67,66.67,66.67
1,25-34,136,50.00,63.24,60.47,76.47,67.53
2,35-44,156,55.13,58.97,62.22,65.12,63.64
3,45-54,148,51.35,58.78,58.82,65.79,62.11
4,55-64,168,56.55,64.29,65.77,76.84,70.87
5,65+,225,43.11,60.89,53.85,64.95,58.88


### Interpretation

The age segment performance test shows moderate variation in model performance across the six age groups. The 45–54 group recorded the lowest accuracy (58.78%) and F1-score (62.11%), while the 55–64 group recorded comparatively stronger performance with an accuracy of 64.29% and F1-score of 70.87%.

However, the differences between the age groups do not show a clear or consistent age-related pattern. The model therefore does not demonstrate a sufficiently strong weakness that would justify refining the feature set based on age alone.

Testing decision: Pass with observation 

Age-related performance variation will be monitored during subsequent validation, but no feature modification will be made solely on the basis of this test.


## 6.5 Appointment day segment performance testing

In [78]:
appointment_day_order = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]

appointment_day_performance = []

for group in appointment_day_order:

    group_data = error_analysis[error_analysis["appointment_day"] == group]

    y_true_group = group_data["actual"]
    y_pred_group = group_data["predicted"]

    appointment_day_performance.append({"Appointment Day": group,
                                        "Total": len(group_data),
                                        "Actual No-Show Rate (%)": round(y_true_group.mean() * 100, 2),
                                        "Accuracy (%)": round(accuracy_score(y_true_group,y_pred_group) * 100, 2),
                                        "Precision (%)": round(precision_score(y_true_group,y_pred_group,
                                                                               zero_division=0) * 100, 2),
                                        "Recall (%)": round(recall_score(y_true_group,y_pred_group,
                                                                         zero_division=0) * 100, 2),
                                        "F1 Score (%)": round(f1_score(y_true_group,y_pred_group,
                                                                       zero_division=0) * 100, 2)
                                       })

appointment_day_performance = pd.DataFrame(appointment_day_performance)

appointment_day_performance

,Appointment Day,Total,Actual No-Show Rate (%),Accuracy (%),Precision (%),Recall (%),F1 Score (%)
0,Monday,126,57.14,66.67,70.83,70.83,70.83
1,Tuesday,132,44.70,65.15,58.67,74.58,65.67
2,Wednesday,153,54.25,62.75,62.75,77.11,69.19
3,Thursday,119,52.94,61.34,62.69,66.67,64.62
4,Friday,140,51.43,55.00,56.00,58.33,57.14
5,Saturday,130,51.54,64.62,65.22,67.16,66.18
6,Sunday,148,46.62,56.08,52.17,69.57,59.63


### Interpretation

The appointment-day segment performance test shows moderate variation in model performance across the seven appointment days. Monday recorded the strongest overall performance, with an accuracy of 66.67% and an F1-score of 70.83%. Friday recorded the weakest performance, with an accuracy of 55.00% and an F1-score of 57.14%. Sunday also showed relatively lower performance, with an accuracy of 56.08% and an F1-score of 59.63%.

Recall varied across the appointment days, ranging from 58.33% on Friday to 77.11% on Wednesday. However, the results do not show a clear or consistent weekday/weekend pattern.

Therefore, although some variation in performance exists across appointment days, there is not sufficient evidence that appointment day represents a major model weakness that independently justifies feature refinement.

Testing decision: Pass with observation 

Appointment-day performance will be monitored during subsequent validation, but no feature modification will be made solely on the basis of these segment-level results.


## 6.6 Appointment time segment performance testing

In [79]:
appointment_time_order = ["Morning","Afternoon","Evening"]

appointment_time_performance = []

for group in appointment_time_order:

    group_data = error_analysis[error_analysis["appointment_time"] == group]

    y_true_group = group_data["actual"]
    y_pred_group = group_data["predicted"]

    appointment_time_performance.append({"Appointment Time": group,
                                         "Total": len(group_data),
                                         "Actual No-Show Rate (%)": round(y_true_group.mean() * 100, 2),
                                         "Accuracy (%)": round(accuracy_score(y_true_group,y_pred_group) * 100, 2),
                                         "Precision (%)": round(precision_score(y_true_group,y_pred_group,
                                                                                zero_division=0) * 100, 2),
                                         "Recall (%)": round(recall_score(y_true_group,y_pred_group,
                                                                          zero_division=0) * 100, 2),
                                         "F1 Score (%)": round(f1_score(y_true_group,y_pred_group,
                                                                        zero_division=0) * 100, 2)
                                        })

appointment_time_performance = pd.DataFrame(appointment_time_performance)

appointment_time_performance

,Appointment Time,Total,Actual No-Show Rate (%),Accuracy (%),Precision (%),Recall (%),F1 Score (%)
0,Morning,417,48.44,59.71,57.26,66.34,61.47
1,Afternoon,382,52.09,62.57,62.50,70.35,66.19
2,Evening,149,56.38,63.76,65.96,73.81,69.66


### Interpretation

The appointment-time segment performance test shows moderate variation in model performance across Morning, Afternoon and Evening appointments. The Morning group recorded the lowest accuracy at 59.71% and the lowest F1-score at 61.47%. The Evening group recorded the strongest performance, with an accuracy of 63.76% and an F1-score of 69.66%.

Recall remained relatively high across all three appointment-time groups, ranging from 66.34% for Morning appointments to 73.81% for Evening appointments. The differences between the groups are moderate and do not indicate a strong or consistent weakness associated with a particular appointment time.

These results are also consistent with the Week 6 analytical finding that appointment time showed relatively limited variation in no-show behaviour. Therefore, appointment time does not provide sufficient evidence to justify an independent feature refinement at this stage.

Testing decision: Pass with observation 

Appointment-time performance will be monitored during subsequent validation, but no feature modification will be made solely on the basis of appointment-time performance.


## 6.7 Distance segment performance testing

In [81]:
distance_group_order = ["0–5 km","6–10 km","11–15 km","16–20 km","21–30 km","31–50 km"]

distance_performance = []

for group in distance_group_order:

    group_data = error_analysis[error_analysis["distance_group"] == group]

    y_true_group = group_data["actual"]
    y_pred_group = group_data["predicted"]

    distance_performance.append({"Distance Group": group,
                                 "Total": len(group_data),
                                 "Actual No-Show Rate (%)": round(y_true_group.mean() * 100, 2),
                                 "Accuracy (%)": round(accuracy_score(y_true_group,y_pred_group) * 100, 2),
                                 "Precision (%)": round(precision_score(y_true_group,y_pred_group,
                                                                        zero_division=0) * 100, 2),
                                 "Recall (%)": round(recall_score(y_true_group,y_pred_group,
                                                                  zero_division=0) * 100, 2),
                                 "F1 Score (%)": round(f1_score(y_true_group,y_pred_group,
                                                                zero_division=0) * 100, 2)
                                })

distance_performance = pd.DataFrame(distance_performance)

distance_performance

,Distance Group,Total,Actual No-Show Rate (%),Accuracy (%),Precision (%),Recall (%),F1 Score (%)
0,0–5 km,207,53.14,60.87,64.95,57.27,60.87
1,6–10 km,342,48.54,64.62,61.54,72.29,66.48
2,11–15 km,218,52.75,56.88,57.89,66.96,62.10
3,16–20 km,97,52.58,59.79,59.38,74.51,66.09
4,21–30 km,69,49.28,66.67,61.22,88.24,72.29
5,31–50 km,15,60.00,53.33,57.14,88.89,69.57


### Interpretation 

The distance-segment performance test shows moderate variation in model performance across the six distance groups.

The 21–30 km group recorded the strongest performance, with an accuracy of 66.67% and an F1-score of 72.29%. The 6–10 km group also performed relatively well, with an accuracy of 64.62% and an F1-score of 66.48%.

The 11–15 km group recorded the lowest accuracy at 56.88%, while the 0–5 km group recorded an accuracy of 60.87%. The 31–50 km group showed a relatively high recall of 88.89%, but this group contains only 15 observations, so the result should be interpreted cautiously.

Overall, the results do not show a clear monotonic relationship between distance and model performance. Although some distance groups show weaker or stronger performance, the differences are not sufficiently consistent to demonstrate that distance is a major independent weakness of the candidate model.

This finding is broadly consistent with the Week 6 error analysis, where distance-related errors varied across groups without showing a clear monotonic pattern.

Testing decision: Pass with observation 

Distance-related performance will be retained for monitoring during subsequent validation, but no feature modification will be made solely on the basis of distance-segment performance.


### 6.8 Overall segment performance testing conclusion

The segment performance tests evaluated the Week 6 Refined Logistic Regression model across booking lead-time groups, previous no-show history, appointment type, age, appointment day, appointment time and distance to the clinic.

The results show that model performance varies across segments, but most differences are moderate and do not provide sufficient evidence for independent feature refinement.

The most notable finding was the variation across booking lead-time groups. The model performed considerably better for appointments booked 31–45 days and 46–60 days in advance, while recall and F1-score were substantially lower for the shorter lead-time groups. This is consistent with the Week 6 analytical and error-testing findings that booking lead time is an important factor in the no-show problem.

Previous no-show history also showed useful variation. Model recall generally increased among patients with previous no-shows, although the 3+ group contains only 18 test observations, requiring caution when interpreting its performance.

Appointment type, age, appointment day and appointment time showed moderate differences between groups but no sufficiently strong or consistent pattern to justify feature modification based on any one of these variables alone.

Distance to the clinic also showed variation across groups. The 31–50 km group produced relatively high recall and F1-score, but it contained only 15 observations, limiting the reliability of the result. No clear monotonic relationship between distance and model performance was observed.

Overall, the segment tests confirm that the candidate model behaves differently across important patient and appointment segments. However, the evidence does not justify making unsupported feature changes at this stage.

Testing decision: Pass with observation 

The candidate model will proceed to robustness and generalisation testing. Booking lead time and previous no-show history will receive particular attention because their segment-level behaviour is more relevant to the intended prediction problem.


# 7. Robustness and generalisation testing

## 7.1 Test-set vs Cross-validation

In [91]:
# Comparing the Week 7 test-set performance with Week 6 cross-validation performance

cv_results = pd.DataFrame({"Metric": ["Accuracy","Precision","Recall",
                                      "F1 Score","ROC-AUC"],
    "Week 7 Test set (%)": [accuracy_score(y_test_refined, y_pred_refined) * 100,
                            precision_score(y_test_refined,y_pred_refined,
                                            zero_division=0) * 100,
                            recall_score(y_test_refined,y_pred_refined,
                                         zero_division=0) * 100,
                            f1_score(y_test_refined,y_pred_refined,
                                     zero_division=0) * 100,
                            roc_auc_score(y_test_refined,y_prob_refined) * 100
                           ],
    "Week 6 5-Fold CV (%)": [61.87,
                             62.47,
                             63.72,
                             63.09,
                             67.45]
})

cv_results["Absolute difference (percentage points)"] = (cv_results["Week 7 Test set (%)"] -cv_results["Week 6 5-Fold CV (%)"]).abs().round(2)

cv_results.round(2)

,Metric,Week 7 Test set (%),Week 6 5-Fold CV (%),Absolute difference (percentage points)
0,Accuracy,61.50,61.87,0.37
1,Precision,60.87,62.47,1.60
2,Recall,69.28,63.72,5.56
3,F1 Score,64.80,63.09,1.71
4,ROC-AUC,66.47,67.45,0.98


### Interpretation

The comparison between the Week 7 test-set performance and the Week 6 5-fold cross-validation results shows generally consistent model performance.

Accuracy differed by only 0.37 percentage points, while precision differed by 1.60 percentage points, F1-score by 1.71 percentage points, and ROC-AUC by 0.98 percentage points.

Recall showed the largest difference, with the Week 7 test-set recall of 69.28% compared with the Week 6 cross-validation recall of 63.72%, representing a difference of 5.56 percentage points.

Although some variation between validation results is expected, the overall pattern does not indicate a substantial deterioration in model performance on the held-out test set. The F1-score and ROC-AUC remain relatively close to the cross-validation results, providing evidence that the candidate model's performance is reasonably consistent across the evaluated validation approaches.

However, the moderate overall performance of the model remains an important limitation. Consistency does not mean that the model is highly accurate; it indicates that the observed performance is not substantially different between the validation approaches used.

Testing decision: Pass with observation 

The candidate model demonstrates reasonably consistent performance between the Week 7 test set and Week 6 cross-validation. No model change is justified solely on the basis of this comparison.


## 7.2 Training vs Test performance

In [93]:
y_train_pred = refined_logistic_model.predict(X_train_refined)
y_train_proba = refined_logistic_model.predict_proba(X_train_refined)[:, 1]

train_test_results = pd.DataFrame({"Metric": ["Accuracy","Precision",
                                              "Recall","F1 Score","ROC-AUC"],
    "Training (%)": [accuracy_score(y_train_refined, y_train_pred) * 100,
                     precision_score(y_train_refined,y_train_pred,
                                     zero_division=0) * 100,
                     recall_score(y_train_refined,y_train_pred,
                                  zero_division=0) * 100,
                     f1_score(y_train_refined,y_train_pred,
                              zero_division=0) * 100,
                     roc_auc_score(y_train_refined,y_train_proba) * 100
                    ],
    "Test (%)": [accuracy_score(y_test_refined, y_pred_refined) * 100,
                 precision_score(y_test_refined,y_pred_refined,
                                 zero_division=0) * 100,
                 recall_score(y_test_refined,y_pred_refined,
                              zero_division=0) * 100,
                 f1_score(y_test_refined,y_pred_refined,
                          zero_division=0) * 100,
                 roc_auc_score(y_test_refined,y_prob_refined) * 100
                ]
})

train_test_results["Difference (percentage points)"] = (train_test_results["Training (%)"] -train_test_results["Test (%)"]).round(2)

train_test_results.round(2)

,Metric,Training (%),Test (%),Difference (percentage points)
0,Accuracy,63.53,61.50,2.03
1,Precision,64.05,60.87,3.19
2,Recall,65.38,69.28,-3.90
3,F1 Score,64.71,64.80,-0.09
4,ROC-AUC,69.59,66.47,3.13


### Interpretation

The training and test results are reasonably close across the evaluated metrics. Accuracy decreases from 63.53% on the training set to 61.50% on the test set, while precision decreases from 64.05% to 60.87% and ROC-AUC decreases from 69.59% to 66.47%.

Recall is slightly higher on the test set (69.28%) than on the training set (65.38%), while the F1-score is almost identical (64.71% training vs 64.80% test).

The relatively small differences between training and test performance do not indicate obvious severe overfitting. The model therefore demonstrates reasonably consistent performance between the data used for fitting and the held-out test data.

However, the overall predictive performance remains moderate. This means that the absence of severe overfitting does not by itself establish that the model is suitable for operational use. Further assessment of cross-validation stability and segment-level performance is still required.

Testing decision: Pass with observation 

The model shows no strong evidence of severe overfitting based on the training-versus-test comparison.


## 7.3 Cross-validation stability testing

In [94]:
# Week 6 5-fold cross-validation results for the refined Logistic Regression model

cv_results = pd.DataFrame({"Metric": ["Accuracy", "Precision",
                                      "Recall", "F1 Score", "ROC-AUC"],
    "Mean CV (%)": [61.87, 62.47, 63.72, 63.09, 67.45],
    "Std CV (%)": [1.26, 1.53, 1.71, 1.22, 1.77]
})

cv_results.round(2)

,Metric,Mean CV (%),Std CV (%)
0,Accuracy,61.87,1.26
1,Precision,62.47,1.53
2,Recall,63.72,1.71
3,F1 Score,63.09,1.22
4,ROC-AUC,67.45,1.77


### Interpretation 

The 5-fold cross-validation results show relatively small variation in model performance across the validation folds. The standard deviations range from 1.22 percentage points for F1-score to 1.77 percentage points for ROC-AUC.

Accuracy has a standard deviation of 1.26 percentage points, while precision and recall have standard deviations of 1.53 and 1.71 percentage points, respectively. These relatively small variations indicate that the refined Logistic Regression model performs reasonably consistently across different subsets of the training data.

The mean cross-validation results were 61.87% accuracy, 62.47% precision, 63.72% recall, 63.09% F1-score and 67.45% ROC-AUC. The results therefore provide additional evidence that the model's performance is reasonably stable rather than being dependent on one particular training-validation split.

However, cross-validation stability does not mean that the model has high predictive performance. The average metrics remain moderate, and the model should therefore continue to be treated as a candidate model rather than a production-ready solution.

Testing decision: Pass with observation

The refined Logistic Regression model demonstrates reasonable cross-validation stability. No model change is required based on cross-validation variability alone.

## 7.4 Overall robustness and generalisation testing conclusion

The Week 7 robustness testing indicates that the refined Logistic Regression model shows reasonable stability and generalisation across the test set, training set and 5-fold cross-validation.

The test-set and cross-validation results were generally close, with the largest difference observed in recall at 5.56 percentage points. The training-versus-test comparison also showed relatively small differences across the main metrics, with no clear evidence of severe overfitting. In addition, the cross-validation standard deviations were relatively small, ranging from 1.22 to 1.77 percentage points, indicating consistent performance across the five folds.

These results provide evidence that the model's performance is not strongly dependent on a single train-test split. However, the overall predictive performance remains moderate, meaning that robustness does not imply that the model is ready for production deployment.

# 8. Testing findings

## 8.1 Summary of testing results

Week 7 testing evaluated the Week 6 refined Logistic Regression candidate across overall model performance, prediction errors, different patient and appointment segments, and robustness/generalisation.

The testing produced the following main findings:

1. Candidate model performance remained consistent with the Week 6 results.
   The refined Logistic Regression achieved 61.50% accuracy, 60.87% precision, 69.28% recall, 64.80% F1-score and 66.47% ROC-AUC on the Week 7 test  set.

2. Error analysis confirmed the presence of both false positives and false negatives.
   The test set contained 216 false positives and 149 false negatives, showing that the model does not perfectly distinguish between attended and no-show appointments.

3. Booking lead time showed the clearest segment-level variation.
   The shorter booking-lead groups had substantially lower recall, while the longer booking-lead groups showed stronger no-show identification. This indicates that model performance varies according to booking lead time.

4. Previous no-show history remained relevant to model performance.
   Performance differed between patients with no previous no-shows and those with previous no-show records. However, the smallest groups require caution because of their limited number of observations.

5. Other segment tests showed moderate variation without a sufficiently strong pattern to justify independent feature changes.
   Appointment type, age, appointment day, appointment time and distance to clinic groups showed differences in performance, but no clear evidence was found that these variables alone required additional refinement.

6. Robustness testing provided evidence of reasonable generalisation.
   Test-set performance was generally close to the 5-fold cross-validation results, while the training versus test comparison did not show evidence of severe overfitting.

7. Cross-validation performance was relatively stable.
   The standard deviations across the five folds ranged from 1.22 to 1.77 percentage points across the evaluated metrics, indicating relatively limited variation between folds.

Overall, the Week 7 testing provides evidence that the refined Logistic Regression model is reasonably stable but remains a moderate-performing candidate. The main areas requiring attention are the model's false-positive and false-negative errors and the variation in performance across booking lead-time groups.

## 8.2 Key issues identified during testing

The Week 7 testing identified several areas that require attention before the HealthConnect model progresses to the next stage.

### 8.2.1 Model prediction errors

The model produced 216 false positives and 149 false negatives on the test set. These errors indicate that the model can incorrectly identify patients as likely to miss an appointment and can also fail to identify some actual no-shows.

These errors should be considered when assessing the practical use of the model and when determining whether targeted refinement is justified.

### 8.2.2 Variation across booking lead-time groups

Booking lead time showed the clearest variation in model performance.

The shorter booking-lead groups had substantially lower recall, particularly the 0–7 day and 8–14 day groups. In contrast, the 31–45 day and 46–60 day groups showed considerably stronger recall.

This suggests that the model does not identify potential no-shows equally well across all booking lead-time groups.

### 8.2.3 Previous no-show history

Performance also varied according to previous no-show history. Patients with previous no-show records showed different prediction behaviour from patients with no previous no-shows.

The 3+ previous no-show group had only 18 observations, so its results should be interpreted cautiously and should not independently drive a modelling change.

### 8.2.4 Moderate overall predictive performance

Although the model demonstrated reasonable stability during robustness testing, its overall predictive performance remains moderate.

The Week 7 test-set ROC-AUC of 66.47% indicates that the model has useful predictive information but does not provide sufficiently strong separation between attended and no-show appointments for unrestricted operational use.

### 8.2.5 No strong evidence for independent refinement of other segments

Testing of appointment type, age, appointment day, appointment time and distance to clinic groups showed some variation in performance.

However, the observed differences did not provide sufficiently strong or consistent evidence to justify changing the model based on any one of these variables independently.

### 8.2.6 Summary of issues requiring attention

The main issues identified during testing are therefore:

* prediction errors involving both false positives and false negatives;
* weaker no-show recall in shorter booking-lead groups;
* variation associated with previous no-show history;
* moderate overall predictive performance; and
* the need to ensure that any refinement is evidence-based rather than based on isolated segment differences.

These findings will guide the refinement process in Section 9. Any model change will be introduced only where the testing evidence provides a clear justification.

## 8.3 Findings requiring refinement vs Findings to monitor

The Week 7 testing results were reviewed to distinguish between findings that provide sufficient evidence for model refinement and findings that should simply be monitored during later testing.

### 8.3.1 Findings requiring refinement

Booking lead-time performance is the main finding requiring further investigation.

The model showed substantially different recall across booking lead-time groups, with weaker no-show identification in the shorter lead-time groups and stronger performance in the longer lead-time groups.

Because booking lead time was also identified as relevant during the Week 6 Data Analytics integration, this finding provides a reasonable basis for targeted refinement rather than introducing an unrelated feature.

The refinement will therefore focus on whether the existing booking lead-time representation can be improved while maintaining the current modelling approach and avoiding data leakage.

### 8.3.2 Findings to monitor

The following findings should be monitored rather than immediately used to modify the model:

* Previous no-show history: performance varies across groups, but the 3+ group contains only 18 observations.
* Appointment type: some variation exists, but no consistent type-specific weakness was identified.
* Age: performance varies between age groups, but there is no clear age-specific pattern requiring refinement.
* Appointment day: performance differs across days, but no consistent weekday or weekend pattern was identified.
* Appointment time: some variation is present, but no strong time-specific weakness was identified.
* Distance to clinic: performance varies between distance groups, but there is no clear monotonic pattern. The 31–50 km group contains only 15 observations and therefore requires caution.

### 8.3.3 Findings not requiring model change

The robustness and generalisation tests did not identify evidence of severe overfitting or unstable cross-validation performance.

Therefore, no model change is required specifically because of:

training versus test performance;
test-set versus cross-validation differences; or
cross-validation variability.

### 8.3.4 Testing decision

Based on the evidence collected during Week 7, targeted refinement is justified for booking lead-time representation, while the other segment findings will be retained as monitoring requirements.

This approach ensures that the next modelling change is based on multiple pieces of evidence rather than on an isolated metric difference.

# 9. Evidence-based refinement

## 9.1 Refinement objective

The Week 7 testing identified booking lead time as the main area requiring further refinement. Model performance varied substantially across the booking lead-time groups, particularly in recall for identifying no-show appointments.

This finding is consistent with the Week 6 Data Analytics integration, where booking lead time was identified as an important factor associated with appointment attendance behaviour.

The objective of this refinement is therefore to improve how booking lead-time information is represented in the model and determine whether this improves prediction performance across the relevant groups.

The refinement will focus on the existing booking lead-time variables rather than introducing unrelated predictors. The model will continue to use the Week 6 refined Logistic Regression approach so that the effect of the targeted feature refinement can be evaluated fairly.

### Refinement objectives

The refinement will aim to:

1. Improve the representation of booking lead-time information,
2. Address the variation in model performance across booking lead-time groups,
3. Maintain the existing preprocessing and modelling structure where appropriate,
4. Avoid data leakage by using only information available at the prediction stage,
5. Compare the refined model against the current Week 7 candidate,
6. Determine whether the refinement produces a meaningful improvement in overall and segment-level performance.

### Expected evaluation

The refined model will be evaluated using:

* Accuracy
* Precision
* Recall
* F1-score
* ROC-AUC
* Confusion matrix
* Booking lead-time segment performance

The refinement will only be retained if the resulting evidence demonstrates a meaningful improvement without introducing new weaknesses.

## 9.2 Review of current booking lead-time features

In [95]:
df[["booking_lead_days", "booking_lead_group", 
    "previous_no_shows","previous_no_show_group",
    "lead_no_show_interaction"]
    ].head(10)

,booking_lead_days,booking_lead_group,previous_no_shows,previous_no_show_group,lead_no_show_interaction
0,12,8–14 days,0,0,8–14 days | 0
1,2,0–7 days,0,0,0–7 days | 0
2,38,31–45 days,1,1,31–45 days | 1
3,41,31–45 days,1,1,31–45 days | 1
4,47,46–60 days,1,1,46–60 days | 1
5,57,46–60 days,2,2,46–60 days | 2
6,30,15–30 days,1,1,15–30 days | 1
7,50,46–60 days,1,1,46–60 days | 1
8,43,31–45 days,0,0,31–45 days | 0
9,16,15–30 days,0,0,15–30 days | 0


In [96]:
# Checking the data types and number of unique values

df[["booking_lead_days", "booking_lead_group", 
    "previous_no_shows","previous_no_show_group",
    "lead_no_show_interaction"]
    ].info()


<class 'pandas.DataFrame'>
RangeIndex: 4737 entries, 0 to 4736
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   booking_lead_days         4737 non-null   int64
 1   booking_lead_group        4737 non-null   str  
 2   previous_no_shows         4737 non-null   int64
 3   previous_no_show_group    4737 non-null   str  
 4   lead_no_show_interaction  4737 non-null   str  
dtypes: int64(2), str(3)
memory usage: 316.0 KB


## 9.3 Feature refinement implementation

In [97]:
# Adding the exact booking lead-time variable to the refined feature set

refined_features_v2 = ['gender','age','age_group','appointment_type','appointment_day',
                       'booking_lead_days','booking_lead_group','previous_appointments',
                       'previous_no_shows','previous_no_show_group','distance_to_clinic_km',
                       'distance_group','lead_no_show_interaction']

X_refined_v2 = df[refined_features_v2]
y_refined_v2 = df["no_show"]

print("Features:", X_refined_v2.shape[1])
print("Observations:", X_refined_v2.shape[0])

Features: 13
Observations: 4737


### 9.3.1 Investigate the booking lead-time representation

In [99]:
# Reviewing the distribution of booking lead-time groups
# together with the observed no-show rate

booking_lead_review = df.groupby("booking_lead_group").agg(total_appointments=("no_show", "count"),
                                                           no_show_count=("no_show", "sum"),
                                                           no_show_rate=("no_show", "mean")).reset_index()

booking_lead_review["no_show_rate (%)"] = (booking_lead_review["no_show_rate"] * 100).round(2)

booking_lead_review[
    [
        "booking_lead_group",
        "total_appointments",
        "no_show_count",
        "no_show_rate (%)"
    ]
]

,booking_lead_group,total_appointments,no_show_count,no_show_rate (%)
0,0–7 days,604,178,29.47
1,15–30 days,1265,576,45.53
2,31–45 days,1187,677,57.03
3,46–60 days,1107,790,71.36
4,8–14 days,574,202,35.19


### 9.3.2 Create a non-Linear booking lead-time feature

In [100]:
# Creating a non-linear representation of booking lead time

df["booking_lead_log"] = np.log1p(df["booking_lead_days"])

df[
    [
        "booking_lead_days",
        "booking_lead_log",
        "booking_lead_group"
    ]
].head(10)

,booking_lead_days,booking_lead_log,booking_lead_group
0,12,2.564949,8–14 days
1,2,1.098612,0–7 days
2,38,3.663562,31–45 days
3,41,3.737670,31–45 days
4,47,3.871201,46–60 days
5,57,4.060443,46–60 days
6,30,3.433987,15–30 days
7,50,3.931826,46–60 days
8,43,3.784190,31–45 days
9,16,2.833213,15–30 days


## 9.4 Build the Week 7 refined feature set

In [101]:
refined_features_week7 = ['gender','age','age_group','appointment_type','appointment_day',
                          'booking_lead_days','booking_lead_group','booking_lead_log',
                          'previous_appointments','previous_no_shows','previous_no_show_group',
                          'distance_to_clinic_km','distance_group','lead_no_show_interaction']

X_week7 = df[refined_features_week7]
y_week7 = df["no_show"]

print("Number of features:", X_week7.shape[1])
print("Number of observations:", X_week7.shape[0])

Number of features: 14
Number of observations: 4737


## 9.5 Train the Week 7 refined Logistic Regression model

In [102]:
# Separating numerical and categorical features

week7_numerical_features = ["age","booking_lead_days","booking_lead_log",
                            "previous_appointments","previous_no_shows",
                            "distance_to_clinic_km"]

week7_categorical_features = ["gender","age_group","appointment_type",
                              "appointment_day","booking_lead_group",
                              "previous_no_show_group","distance_group",
                              "lead_no_show_interaction"]

print("Numerical features:", len(week7_numerical_features))
print("Categorical features:", len(week7_categorical_features))

Numerical features: 6
Categorical features: 8


In [107]:
# Creating the preprocessing pipeline
week7_preprocessor = ColumnTransformer(transformers=[("num", StandardScaler(), week7_numerical_features),
                                                     ("cat", OneHotEncoder(handle_unknown="ignore"), week7_categorical_features)
                                                    ])
week7_preprocessor

,"transformers transformers: list of tuplesList of (name, transformer, columns) tuples specifying thetransformer objects to be applied to subsets of the data.name : str Like in Pipeline and FeatureUnion, this allows the transformer and its parameters to be set using ``set_params`` and searched in grid search.transformer : {'drop', 'passthrough'} or estimator Estimator must support :term:`fit` and :term:`transform`. Special-cased strings 'drop' and 'passthrough' are accepted as well, to indicate to drop the columns or to pass them through untransformed, respectively.columns : str, array-like of str, int, array-like of int, array-like of bool, slice or callable Indexes the data on its second axis. Integers are interpreted as positional columns, while strings can reference DataFrame columns by name. A scalar string or int should be used where ``transformer`` expects X to be a 1d array-like (vector), otherwise a 2d array will be passed to the transformer. A callable is passed the input data `X` and can return any of the above. To select multiple columns by name or dtype, you can use :obj:`make_column_selector`.","[('num', ...), ('cat', ...)]"
,"remainder remainder: {'drop', 'passthrough'} or estimator, default='drop'By default, only the specified columns in `transformers` aretransformed and combined in the output, and the non-specifiedcolumns are dropped. (default of ``'drop'``).By specifying ``remainder='passthrough'``, all remaining columns thatwere not specified in `transformers`, but present in the data passedto `fit` will be automatically passed through. This subset of columnsis concatenated with the output of the transformers. For dataframes,extra columns not seen during `fit` will be excluded from the outputof `transform`.By setting ``remainder`` to be an estimator, the remainingnon-specified columns will use the ``remainder`` estimator. Theestimator must support :term:`fit` and :term:`transform`.Note that using this feature requires that the DataFrame columnsinput at :term:`fit` and :term:`transform` have identical order.",'drop'
,"sparse_threshold sparse_threshold: float, default=0.3If the output of the different transformers contains sparse matrices,these will be stacked as a sparse matrix if the overall density islower than this value. Use ``sparse_threshold=0`` to always returndense. When the transformed output consists of all dense data, thestacked result will be dense, and this keyword will be ignored.",0.3
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.",None
,"transformer_weights transformer_weights: dict, default=NoneMultiplicative weights for features per transformer. The output of thetransformer is multiplied by these weights. Keys are transformer names,values the weights.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each transformer will beprinted as it is completed.",False
,"verbose_feature_names_out verbose_feature_names_out: bool, str or Callable[[str, str], str], default=True- If True, :meth:`ColumnTransformer.get_feature_names_out` will prefix all feature names with the name of the transformer that generated that feature. It is equivalent to setting `verbose_feature_names_out=""{transformer_name}__{feature_name}""`.- If False, :meth:`ColumnTransformer.get_feature_names_out` will not prefix any feature names and will error if feature names are not unique.- If ``Callable[[str, str], str]``, :meth:`ColumnTransformer.get_feature_names_out` will rename all the features using the name of the transformer. The first argument of the callable is the transformer name and the second argument is the feature name. The returned string will be the new feature name.- If ``str``, it must be a string ready for formatting. The given string will be formatted using two field names: ``transformer_name`` and ``feature_name``

In [108]:
# Creating the week7_logistic_model

week7_logistic_model = Pipeline(steps=[("preprocessor", week7_preprocessor),
                                       ("classifier", LogisticRegression(max_iter=1000,
                                                                         random_state=42))
                                      ]
                               )

week7_logistic_model

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('preprocessor', ...), ('classifier', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
,"transformers transformers: list of tuplesList of (name, transformer, columns) tuples specifying thetransformer objects to be applied to subsets of the data.name : str Like in Pipeline and FeatureUnion, this allows the transformer and its parameters to be set using ``set_params`` and searched in grid search.transformer : {'drop', 'passthrough'} or estimator Estimator must support :term:`fit` and :term:`transform`. Special-cased strings 'drop' and 'passthrough' are accepted as well, to indicate to drop the columns or to pass them through untransformed, respectively.columns : str, array-like of str, int, array-like of int, array-like of bool, slice or callable Indexes the data on its second axis. Integers are interpreted as positional columns, while strings can reference DataFrame columns by name. A scalar string or int should be used where ``transformer`` expects X to be a 1d array-like (vector), otherwise a 2d array will be passed to the transformer. A callable is passed the input data `X` and can return any of the above. To select multiple columns by name or dtype, you can use :obj:`make_column_selector`.","[('num', ...), ('cat', ...)]"
,"remainder remainder: {'drop', 'passthrough'} or estimator, default='drop'By default, only the specified columns in `transformers` aretransformed and combined in the output, and the non-specifiedcolumns are dropped. (default of ``'drop'``).By specifying ``remainder='passthrough'``, all remaining columns thatwere not specified in `transformers`, but present in the data passedto `fit` will be automatically passed through. This subset of columnsis concatenated with the output of the transformers. For dataframes,extra columns not seen during `fit` will be excluded from the outputof `transform`.By setting ``remainder`` to be an estimator, the remainingnon-specified columns will use the ``remainder`` estimator. Theestimator must support :term:`fit` and :term:`transform`.Note that using this feature requires that the DataFrame columnsinput at :term:`fit` and :term:`transform` have identical order.",'drop'
,"sparse_threshold sparse_threshold: float, default=0.3I

In [109]:
# Train-test split using the same 80/20 stratified split
X_train_week7, X_test_week7, y_train_week7, y_test_week7 = train_test_split(X_week7,y_week7,
                                                                            test_size=0.20,
                                                                            random_state=42,
                                                                            stratify=y_week7)

print("Training observations:", X_train_week7.shape[0])
print("Testing observations:", X_test_week7.shape[0])

Training observations: 3789
Testing observations: 948


In [110]:
# Training the Week 7 refined Logistic Regression model

week7_logistic_model.fit(X_train_week7, y_train_week7)

print("Week 7 refined Logistic Regression model trained successfully.")

Week 7 refined Logistic Regression model trained successfully.


## 9.6 Evaluate the Week 7 refined model

In [112]:
# Generating the Week 7 predictions and probabilities

y_pred_week7 = week7_logistic_model.predict(X_test_week7)
y_pred_proba_week7 = week7_logistic_model.predict_proba(X_test_week7)[:, 1]

print("Predictions generated successfully.")

Predictions generated successfully.


In [113]:
week7_metrics = pd.DataFrame({"Metric": ["Accuracy","Precision",
                                         "Recall","F1 Score","ROC-AUC"
                                        ],
    "Week 7 (%)": [accuracy_score(y_test_week7, y_pred_week7) * 100,
                   precision_score(y_test_week7, y_pred_week7) * 100,
                   recall_score(y_test_week7, y_pred_week7) * 100,
                   f1_score(y_test_week7, y_pred_week7) * 100,
                   roc_auc_score(y_test_week7, y_pred_proba_week7) * 100
                  ]
})

week7_metrics.round(2)

,Metric,Week 7 (%)
0,Accuracy,61.50
1,Precision,60.91
2,Recall,69.07
3,F1 Score,64.73
4,ROC-AUC,66.52


In [144]:
week7_cm = confusion_matrix(y_test_week7,y_pred_week7)
print("Week 7 confusion matrix:")
print(week7_cm)

Week 7 confusion matrix:
[[248 215]
 [150 335]]


### Interpretation

The Week 7 Logistic Regression model produced results that were very similar to the Week 6 candidate model.

Accuracy remained unchanged at 61.50%. Precision increased slightly from 60.87% to 60.91%, while recall decreased from 69.28% to 69.07%. F1-score decreased slightly from 64.80% to 64.73%, while ROC-AUC increased marginally from 66.47% to 66.52%.

The confusion matrix also showed only minor changes, with one additional true negative, one fewer false positive, one additional false negative and one fewer true positive.

These changes are very small and do not provide evidence of a meaningful overall performance improvement from the booking_lead_log feature.

Decision: refinement not retained based on overall performance

The Week 7 refinement will therefore require further investigation at the segment level before deciding whether the new feature should be retained. This ensures that the model is not changed solely because a new feature produces marginal numerical differences.


## 9.7 Segment-level refinement check

In [115]:
# Adding the booking lead-time groups to the Week 7 test results

week7_segment_test = X_test_week7.copy()

week7_segment_test["actual"] = y_test_week7.values
week7_segment_test["predicted"] = y_pred_week7

week7_segment_test.groupby("booking_lead_group").agg(total=("actual", "count"), actual_no_shows=("actual", "sum")).reset_index()

,booking_lead_group,total,actual_no_shows
0,0–7 days,119,33
1,15–30 days,228,105
2,31–45 days,249,135
3,46–60 days,243,172
4,8–14 days,109,40


In [116]:
week7_booking_results = []

for group in sorted(week7_segment_test["booking_lead_group"].unique()):
    
    group_data = week7_segment_test[week7_segment_test["booking_lead_group"] == group]
    
    y_true_group = group_data["actual"]
    y_pred_group = group_data["predicted"]
    
    week7_booking_results.append({"Booking Lead Group": group,
                                  "Total": len(group_data),
                                  "Accuracy (%)": accuracy_score(y_true_group, y_pred_group) * 100,
                                  "Precision (%)": precision_score(y_true_group, y_pred_group, 
                                                                   zero_division=0) * 100,
                                  "Recall (%)": recall_score(y_true_group, y_pred_group, 
                                                             zero_division=0) * 100,
                                  "F1 Score (%)": f1_score(y_true_group, y_pred_group, 
                                                           zero_division=0) * 100
                                 })

week7_booking_results = pd.DataFrame(week7_booking_results)

week7_booking_results.round(2)

,Booking Lead Group,Total,Accuracy (%),Precision (%),Recall (%),F1 Score (%)
0,0–7 days,119,75.63,75.00,18.18,29.27
1,15–30 days,228,52.19,46.88,28.57,35.50
2,31–45 days,249,53.01,53.98,90.37,67.59
3,46–60 days,243,70.78,70.78,100.00,82.89
4,8–14 days,109,64.22,55.56,12.50,20.41


## 9.8 Refinement decision

The Week 7 booking_lead_log refinement was evaluated against the Week 6 refined Logistic Regression candidate using both overall model performance and booking lead-time segment performance.

The overall metrics showed only marginal changes. Accuracy remained at 61.50%, while precision increased by 0.04 percentage points and ROC-AUC increased by 0.05 percentage points. Recall and F1-score decreased slightly.

Segment-level testing also failed to demonstrate a consistent improvement across the booking lead-time groups. Although recall increased by 3.03 percentage points in the 0–7 day group, the 8–14 day group showed no change, while recall decreased slightly in the 15–30 day and 31–45 day groups.

Therefore, the evidence does not support retaining booking_lead_log as a meaningful improvement to the Week 6 candidate model.

Refinement decision: Reject the booking_lead_log

The Week 6 refined Logistic Regression model will remain the candidate model. The rejected refinement will nevertheless be documented as a Week 7 testing outcome because it demonstrates that an evidence-based feature refinement was tested and evaluated rather than assumed to be beneficial.

The identified weakness in shorter booking lead-time groups will remain a monitoring requirement for future testing, rather than being addressed through an unsupported feature change.

The next step is to re-test and confirm the retained Week 6 candidate model, ensuring that the final candidate for Week 7 remains the model that demonstrated the strongest evidence from the completed testing activities.

# 10. Re-testing

## 10.1 Re-testing objective

The purpose of the re-testing stage is to confirm the performance and behaviour of the retained Week 6 candidate model after the Week 7 refinement process.

The Week 7 booking_lead_log feature was evaluated as a targeted refinement because booking lead time showed a meaningful relationship with appointment attendance and variation in model performance across booking lead-time groups. However, the refinement produced only marginal changes in overall performance and did not consistently improve performance across the affected segments.

The booking_lead_log feature was therefore not retained in the final candidate model.

The Week 6 Refined Logistic Regression model will now be re-tested to confirm that the retained candidate continues to perform consistently after the refinement decision.

The re-testing will focus on:

* confirming the retained model's overall classification performance;
* confirming the confusion matrix;
* comparing the re-tested results with the previously established Week 6 results;
* verifying that the rejected refinement has not been incorporated into the final candidate;
* confirming that the model remains stable enough to proceed to final suitability assessment.

This re-test is a confirmation of the retained candidate rather than a new independent validation dataset. The same held-out test set used during the Week 6 and Week 7 model comparisons is retained for consistency of comparison.


## 10.2 Re-testing the retained Week 6 refined Logistic Regression model

In [117]:
y_pred_retest = refined_logistic_model.predict(X_test_refined)
y_proba_retest = refined_logistic_model.predict_proba(X_test_refined)[:, 1]

retest_results = pd.DataFrame({"Metric": ["Accuracy","Precision","Recall","F1 Score","ROC-AUC"],
    "Re-test (%)": [accuracy_score(y_test_refined, y_pred_retest) * 100,
                    precision_score(y_test_refined, y_pred_retest) * 100,
                    recall_score(y_test_refined, y_pred_retest) * 100,
                    f1_score(y_test_refined, y_pred_retest) * 100,
                    roc_auc_score(y_test_refined, y_proba_retest) * 100
                   ]
})

retest_results.round(2)

,Metric,Re-test (%)
0,Accuracy,61.50
1,Precision,60.87
2,Recall,69.28
3,F1 Score,64.80
4,ROC-AUC,66.47


## 10.3 Re-test confusion matrix

In [119]:
cm_retest = confusion_matrix(y_test_refined, y_pred_retest)

cm_retest

array([[247, 216],
       [149, 336]])

## 10.4 Before vs after refinement

The Week 7 refinement introduced booking_lead_log, a logarithmic transformation of booking_lead_days, to provide an alternative representation of the strong ordered relationship observed between booking lead time and appointment no-show behaviour.

The refined Week 7 model was compared with the retained Week 6 Refined Logistic Regression model.

| Metric    | Week 6 candidate | Week 7 refinement |   Change |
| --------- | ---------------: | ----------------: | -------: |
| Accuracy  |           61.50% |            61.50% |  0.00 pp |
| Precision |           60.87% |            60.91% | +0.04 pp |
| Recall    |           69.28% |            69.07% | −0.21 pp |
| F1 Score  |           64.80% |            64.73% | −0.07 pp |
| ROC-AUC   |           66.47% |            66.52% | +0.05 pp |

The Week 7 refinement produced only marginal changes in overall model performance. Accuracy remained unchanged, while the changes in precision, recall, F1-score and ROC-AUC were very small.

The confusion matrix of the retained Week 6 candidate was also reproduced exactly during re-testing:

```text
[[247, 216],
 [149, 336]]
```

This confirms that the retained candidate model continues to produce the same classification behaviour observed during Week 6.

The segment-level testing also did not provide sufficient evidence that the booking_lead_log feature consistently improved performance across booking lead-time groups. Some groups showed small changes, while others showed no improvement or slightly lower performance.

Therefore, the booking_lead_log refinement was rejected and the Week 6 refined Logistic Regression model remains the retained candidate model.

The refinement process nevertheless provided useful evidence: the strong relationship between booking lead time and no-show behaviour remains important for monitoring and future model development, but the logarithmic transformation did not provide sufficient additional predictive value in the current model.

The retained Week 6 candidate has been successfully re-tested and reproduced its original performance. No further model modification is justified based on the Week 7 refinement that was evaluated.


## 10.5 Re-testing conclusion

The retained Week 6 Refined Logistic Regression model was successfully re-tested using the same held-out test set used during the previous evaluation.

The re-test reproduced the Week 6 results exactly:

* Accuracy: 61.50%
* Precision: 60.87%
* Recall: 69.28%
* F1 Score: 64.80%
* ROC-AUC: 66.47%

The confusion matrix was also reproduced exactly:

```text
[[247, 216],
 [149, 336]]
```

This confirms that the retained candidate model is reproducible within the current testing setup.

The Week 7 booking_lead_log refinement was not retained because it produced only marginal overall changes and did not consistently improve performance across booking lead-time segments. The re-testing therefore confirms that the Week 6 Refined Logistic Regression remains the appropriate candidate to carry forward from the current refinement cycle.

However, the model's performance remains moderate. The re-test does not establish that the model is ready for production deployment or real-world clinical use. Further validation using independent and representative real-world data, temporal validation, calibration assessment and threshold evaluation would still be required before operational use.


# 11. Cross-track testing

## 11.1 Data Analytics dependency

The Week 7 Data Science track established a two-way cross-track dependency with the Data Analytics track. The Data Analytics team provided validated analytical findings to support Data Science testing and feature refinement, while Data Science provided model structure, evaluation results and refinement outcomes back to Data Analytics to support the broader HealthConnect project.

### Information received from Data Analytics

The Data Analytics analysis identified booking lead time and previous no-show history as the two strongest and most reliable predictors of appointment no-shows.

Booking lead time showed the strongest single-variable relationship with the no-show outcome, with a point-biserial correlation of r = 0.272 and a statistically significant association with no-show outcome (χ² = 364.81, p < 0.001). Previous no-show history also showed a statistically significant relationship, with r = 0.126 and χ² = 80.71, p < 0.001.

The findings were relevant to the Data Science model because both variables were already included in the Week 6 candidate model. The Data Analytics team further identified the 15–30 day and 31–45 day booking lead-time bands as important middle-risk segments where classification decisions may be more difficult.

The Data Analytics team also examined the combined effect of booking lead time and previous no-show history and reported that the effects were additive rather than multiplicative. They therefore recommended considering a simple summed risk score rather than relying on a complex interaction term.

These findings created a specific dependency for Data Science: the analytical evidence needed to be tested against the existing model features and used to determine whether the current representation of booking lead time and previous no-show history was appropriate.

### Information provided to Data Analytics

In return, the Data Science track provided the Data Analytics team with the results of the Week 7 modelling and validation work.

The information provided included:

* The 13 features used by the retained Week 6 Refined Logistic Regression candidate.
* The target definition, where no_show = 1 represents a No-Show and no_show = 0 represents an Attended appointment.
* Confirmation that cancelled appointments were excluded from modelling.
* The retained lead_no_show_interaction feature combining booking lead group and previous no-show group.
* The Week 6 candidate model performance:

  * Accuracy: 61.50%
  * Precision: 60.87%
  * Recall: 69.28%
  * F1-score: 64.80%
  * ROC-AUC: 66.47%
* The confusion matrix:

  * True Negatives: 247
  * False Positives: 216
  * False Negatives: 149
  * True Positives: 336
* Evidence from Week 7 testing showing how the model performed across booking lead-time groups.
* The results of the Week 7 booking_lead_log refinement.
* The decision to reject the logarithmic transformation because it produced only marginal overall changes and did not consistently improve performance across booking lead-time groups.
* The conclusion that the Week 6 Refined Logistic Regression remained the retained candidate model.

### How the Analytics findings Influenced Data Science

The Data Analytics findings directly influenced the Week 7 modelling investigation.

Previous No-Shows:
The finding that previous no-show history was significantly associated with appointment attendance supported retaining previous_no_shows and previous_no_show_group in the model. It also supported the continued investigation of their relationship with booking lead time.

Booking Lead Days:
The strong ordered relationship identified by Data Analytics motivated further investigation of the booking lead-time representation. In the modelling dataset, no-show rates increased from 29.47% for appointments booked 0–7 days in advance to 71.36% for appointments booked 46–60 days in advance. This evidence directly motivated the Week 7 testing of the additional booking_lead_log feature.

Reminder Sent:
Although reminder information was relevant to the broader analytical investigation, reminder_sent was not included as a predictive feature. Its availability at prediction time creates a potential prediction-time and data-leakage concern. It was therefore not used as part of the retained prediction model.

## 11.2 Create the additive risk score

In [127]:
# Assigning ordinal scores to the existing booking lead-time groups

lead_score_map = {"0–7 days": 0,"8–14 days": 1,"15–30 days": 2,"31–45 days": 3,"46–60 days": 4}

df["booking_lead_score"] = df["booking_lead_group"].map(lead_score_map)


# Assigning ordinal scores to the existing previous no-show groups

previous_no_show_score_map = {"0": 0,"1": 1,"2": 2,"3+": 3}

df["previous_no_show_score"] = (df["previous_no_show_group"].map(previous_no_show_score_map))


# Creating the combined additive score

df["lead_no_show_score"] = (df["booking_lead_score"] + df["previous_no_show_score"])


# Checking the newly created variables

df[["booking_lead_group","booking_lead_score","previous_no_show_group",
    "previous_no_show_score","lead_no_show_score"]].head(10)

,booking_lead_group,booking_lead_score,previous_no_show_group,previous_no_show_score,lead_no_show_score
0,8–14 days,1,0,0,1
1,0–7 days,0,0,0,0
2,31–45 days,3,1,1,4
3,31–45 days,3,1,1,4
4,46–60 days,4,1,1,5
5,46–60 days,4,2,2,6
6,15–30 days,2,1,1,3
7,46–60 days,4,1,1,5
8,31–45 days,3,0,0,3
9,15–30 days,2,0,0,2


In [126]:
# Defining the Week 7 collaborative feature set
# Replacing the interaction feature with the additive risk score

collaborative_features = ['gender','age','age_group','appointment_type','appointment_day',
                          'booking_lead_days','booking_lead_group','previous_appointments',
                          'previous_no_shows','previous_no_show_group','distance_to_clinic_km',
                          'distance_group','lead_no_show_score']

X_collaborative = df[collaborative_features]
y_collaborative = df["no_show"]

print("Features:", X_collaborative.shape[1])
print("Observations:", X_collaborative.shape[0])

Features: 13
Observations: 4737


### 11.2.1 Train the collaborative model

In [130]:
# Defining the numerical and categorical features

collaborative_numerical_features = ["age","booking_lead_days","previous_appointments",
                                    "previous_no_shows","distance_to_clinic_km",
                                    "lead_no_show_score"]

collaborative_categorical_features = ["gender","age_group","appointment_type",
                                      "appointment_day","booking_lead_group",
                                      "previous_no_show_group","distance_group"]


# Creating the preprocessing pipeline

collaborative_preprocessor = ColumnTransformer(transformers=[("num",StandardScaler(),
                                                              collaborative_numerical_features),
                                                             ("cat",OneHotEncoder(handle_unknown="ignore"),
                                                              collaborative_categorical_features)])


# Creating the collaborative Logistic Regression model

collaborative_logistic_model = Pipeline(steps=[("preprocessor",collaborative_preprocessor),
                                               ("classifier",LogisticRegression(max_iter=1000,
                                                                                random_state=42))])


# Using the same train-test split as the Week 6 candidate

X_train_collaborative, X_test_collaborative,y_train_collaborative, y_test_collaborative = train_test_split(X_collaborative,y_collaborative,
                                                               test_size=0.20,
                                                               random_state=42,
                                                               stratify=y_collaborative)


# Training the model

collaborative_logistic_model.fit(X_train_collaborative,y_train_collaborative)

print("Collaborative Logistic Regression model trained successfully.")

Collaborative Logistic Regression model trained successfully.


### 11.2.2 Evaluate the collaborative model

In [131]:
# Generating predictions and probabilities

y_pred_collaborative = collaborative_logistic_model.predict(X_test_collaborative)

y_pred_proba_collaborative = collaborative_logistic_model.predict_proba(X_test_collaborative)[:, 1]


# Calculating evaluation metrics

collaborative_accuracy = accuracy_score(y_test_collaborative,y_pred_collaborative)

collaborative_precision = precision_score(y_test_collaborative,y_pred_collaborative)

collaborative_recall = recall_score(y_test_collaborative,y_pred_collaborative)

collaborative_f1 = f1_score(y_test_collaborative,y_pred_collaborative)

collaborative_roc_auc = roc_auc_score(y_test_collaborative,y_pred_proba_collaborative)

print("Collaborative model results")
print("---------------------------")
print(f"Accuracy:  {collaborative_accuracy:.4f}")
print(f"Precision: {collaborative_precision:.4f}")
print(f"Recall:    {collaborative_recall:.4f}")
print(f"F1 Score:  {collaborative_f1:.4f}")
print(f"ROC-AUC:   {collaborative_roc_auc:.4f}")

Collaborative model results
---------------------------
Accuracy:  0.6118
Precision: 0.6073
Recall:    0.6825
F1 Score:  0.6427
ROC-AUC:   0.6639


### 11.2.3 Collaborative test comparison

In [133]:
# Comparing the Week 6 candidate with the Analytics-informed collaborative model

collaborative_comparison = pd.DataFrame({"Metric": ["Accuracy","Precision",
                                                    "Recall","F1 Score",
                                                    "ROC-AUC"],
    "Week 6 candidate (%)": [61.50,60.87,69.28,64.80,66.47],
    "Collaborative model (%)": [61.18,60.73,68.25,64.27,66.39]
                                        })

collaborative_comparison["Difference (percentage points)"] = (collaborative_comparison["Collaborative model (%)"]
                                                              - collaborative_comparison["Week 6 candidate (%)"]
                                                             ).round(2)

collaborative_comparison

,Metric,Week 6 candidate (%),Collaborative model (%),Difference (percentage points)
0,Accuracy,61.50,61.18,-0.32
1,Precision,60.87,60.73,-0.14
2,Recall,69.28,68.25,-1.03
3,F1 Score,64.80,64.27,-0.53
4,ROC-AUC,66.47,66.39,-0.08


## 11.3 Collaborative test finding

The Data Analytics findings were incorporated into the Data Science modelling workflow by testing a simple additive risk score based on the validated booking lead-time groups and previous no-show groups.

The collaborative model was evaluated against the retained Week 6 Logistic Regression candidate using the same modelling dataset, target variable and 80/20 stratified train-test approach.

The collaborative model achieved:

* Accuracy: 61.18%
* Precision: 60.73%
* Recall: 68.25%
* F1-score: 64.27%
* ROC-AUC: 66.39%

Compared with the Week 6 candidate, the collaborative model showed small decreases across all five metrics. The largest difference was a 1.03 percentage-point decrease in recall, while ROC-AUC decreased by only 0.08 percentage points.

Therefore, the test did not provide evidence that replacing the existing lead_no_show_interaction representation with the tested additive score improves overall predictive performance.

The result should not be interpreted as evidence that booking lead time or previous no-show history are unimportant. The Data Analytics findings identified these variables as meaningful predictors and the Week 7 test instead indicates that this specific additive representation did not improve the existing model.

Testing decision: no measurable improvement demonstrated.


## 11.4 Collaborative test action

Based on the collaborative test results, the tested lead_no_show_score representation will not replace the Week 6 lead_no_show_interaction feature in the candidate model.

The Week 6 refined Logistic Regression model will therefore remain the retained candidate for the next validation stage.

The Data Analytics findings will nevertheless remain part of the documented modelling evidence. In particular, booking lead time and previous no-show history will continue to be monitored during subsequent testing because the cross-track evidence indicates that these variables contain useful information about no-show behaviour.

The unsuccessful additive-score test will also be retained as evidence of Week 7 model refinement and decision-making. This demonstrates that the cross-track recommendation was tested empirically rather than being adopted without validation.

## 11.5 Re-test the retained Week 6 candidate model

In [136]:
y_pred_retest = refined_logistic_model.predict(X_test_refined)
y_pred_proba_retest = refined_logistic_model.predict_proba(X_test_refined)[:, 1]

retest_accuracy = accuracy_score(y_test_refined,y_pred_retest)

retest_precision = precision_score(y_test_refined,y_pred_retest)

retest_recall = recall_score(y_test_refined,y_pred_retest)

retest_f1 = f1_score(y_test_refined,y_pred_retest)

retest_roc_auc = roc_auc_score(y_test_refined,y_pred_proba_retest)

print("Retest results")
print("--------------")
print(f"Accuracy:  {retest_accuracy:.4f}")
print(f"Precision: {retest_precision:.4f}")
print(f"Recall:    {retest_recall:.4f}")
print(f"F1 Score:  {retest_f1:.4f}")
print(f"ROC-AUC:   {retest_roc_auc:.4f}")

Retest results
--------------
Accuracy:  0.6150
Precision: 0.6087
Recall:    0.6928
F1 Score:  0.6480
ROC-AUC:   0.6647


### Interpretation

Following the collaborative test, the Week 6 refined Logistic Regression candidate was re-tested using the retained modelling workflow and held-out test set.

The retest reproduced the Week 6 candidate results exactly:

* Accuracy: 61.50%
* Precision: 60.87%
* Recall: 69.28%
* F1-score: 64.80%
* ROC-AUC: 66.47%

The results confirm that rejecting the tested additive lead_no_show_score representation did not alter the retained candidate model. The Week 6 candidate remains reproducible and provides a consistent benchmark for the next stage of HealthConnect validation.

Because the same held-out test set was used, this retest should be interpreted as a confirmation of reproducibility, rather than as an independent validation on new data.

## 11.6 Validated improvement

The Week 7 cross-track testing activity produced a validated modelling decision rather than a direct increase in predictive performance.

The Data Analytics recommendation concerning booking lead time and previous no-show history was incorporated into the Data Science workflow and tested through an additive risk-score representation. The collaborative model did not improve the Week 6 candidate, with small decreases observed across accuracy, precision, recall, F1-score and ROC-AUC.

The additive representation was therefore rejected, while the Week 6 refined Logistic Regression model was retained. A subsequent retest reproduced the Week 6 candidate results exactly.

The validated improvement from the cross-track activity is therefore the evidence-based refinement of the modelling approach and decision process. The collaboration demonstrated that an Analytics finding can be translated into a modelling experiment, evaluated objectively and either retained or rejected based on evidence.

This activity also clarified that identifying an important predictor does not necessarily mean that every possible representation of that predictor will improve model performance.

Cross-track testing status: Pass 

The recommendation was tested, outcomes were documented, action was taken, and the retained candidate was successfully re-tested.


# 12. Model suitability assessment

## 12.1 Define the suitability criteria

In [145]:
# Displaying the model suitability evidence clearly

suitability_evidence = pd.DataFrame({"Criterion": ["Overall predictive performance",
                                                   "False-positive / false-negative behaviour",
                                                   "Segment performance",
                                                   "Robustness and generalisation",
                                                   "Business relevance","Production readiness"
                                                  ],
                                     
    "Evidence": ["Accuracy 61.50%, Precision of 60.87%, F1-score 64.80%, and ROC-AUC 66.47%.",
                 "The model produced 216 false positives and 149 false negatives.",
                 "Performance varies across booking lead-time and other patient/appointment segments.",
                 "Test-set, training-set and 5-fold cross-validation results show reasonable stability.",
                 "The model can support identification of appointments that may require additional attention.",
                 "Further validation is required before production use."]
})

# Preventing pandas from truncating the evidence column
pd.set_option("display.max_colwidth", None)

suitability_evidence

,Criterion,Evidence
0,Overall predictive performance,"Accuracy 61.50%, Precision of 60.87%, F1-score 64.80%, and ROC-AUC 66.47%."
1,False-positive / false-negative behaviour,The model produced 216 false positives and 149 false negatives.
2,Segment performance,Performance varies across booking lead-time and other patient/appointment segments.
3,Robustness and generalisation,"Test-set, training-set and 5-fold cross-validation results show reasonable stability."
4,Business relevance,The model can support identification of appointments that may require additional attention.
5,Production readiness,Further validation is required before production use.


## 12.2 Suitability assessment

The retained Week 6 refined Logistic Regression model was assessed against the defined HealthConnect requirements using the Week 7 testing evidence.

The model achieved an accuracy of 61.50%, precision of 60.87%, recall of 69.28%, F1-score of 64.80%, and ROC-AUC of 66.47% on the held-out test set. These results indicate that the model provides meaningful predictive information about appointment no-show behaviour, but its overall predictive performance remains moderate.

The error analysis identified 216 false positives and 149 false negatives. This demonstrates that the model can identify a substantial proportion of no-show appointments, but it also makes incorrect predictions in both directions. These errors would need to be considered carefully if predictions were used to support patient-contact or appointment-support decisions.

Segment testing showed variation in model performance across booking lead-time groups and other patient and appointment segments. In particular, shorter booking lead-time groups showed relatively low recall, while longer booking lead-time groups showed stronger recall. This indicates that model performance is not completely uniform across all appointment groups.

The robustness testing provided evidence of reasonable model stability. Test-set performance was broadly consistent with the Week 6 cross-validation results, training and test performance did not show evidence of severe overfitting, and cross-validation results showed relatively small variation across folds.

The cross-track testing with Data Analytics also demonstrated that relevant analytical findings could be incorporated into the modelling workflow and evaluated empirically. The tested additive risk-score representation did not improve the retained candidate, so it was rejected and the Week 6 candidate was retained.

Based on the evidence available in Week 7, the model is suitable as a candidate decision-support model for further testing and refinement, but it should not yet be considered production-ready. Further validation using additional or temporally separated data, assessment of prediction thresholds and calibration, and continued monitoring of false positives, false negatives and segment-level performance would be required before practical deployment.

Suitability decision: Suitable for continued testing and development but not yet suitable for production deployment.

## 12.3 Model strengths and weaknesses

The retained Week 6 Refined Logistic Regression model has several strengths that support its continued use as a candidate model for the HealthConnect project. The model is reproducible, interpretable and showed reasonably consistent performance across the held-out test set, training set and 5-fold cross-validation. The test-set recall of 69.28% indicates that the model identifies a substantial proportion of appointments that result in a no-show. The model also incorporates relevant findings from the Data Analytics track, including booking lead time and previous no-show history.

However, the model also has important weaknesses. Overall predictive performance remains moderate, with a test-set accuracy of 61.50%, F1-score of 64.80% and ROC-AUC of 66.47%. The model produced 216 false positives and 149 false negatives, meaning that some patients would be incorrectly identified as likely to miss their appointments while others who actually miss appointments would not be identified.

Performance also varies across patient and appointment segments. In particular, shorter booking lead-time groups showed relatively low recall, indicating that the model may have difficulty identifying some no-shows among appointments booked closer to the appointment date. This should remain an area for monitoring during subsequent testing.

The model has also not yet been independently validated on a temporally separated or external dataset. In addition, probability calibration and alternative classification thresholds have not yet been fully evaluated. These limitations mean that the model should currently be treated as a candidate decision-support model rather than a production-ready predictive system.

Overall, the testing results support continued development of the model while highlighting specific areas that require further validation before operational deployment

# 13. Limitations and risks

The Week 7 testing process identified several limitations and risks that should be considered before the HealthConnect model is used in a real operational environment.

## 13.1 Data limitations

The HealthConnect dataset is a fictional project dataset. Therefore, the observed relationships and model performance cannot be assumed to represent the behaviour of patients in a real healthcare environment.

The current evaluation is also based on the available dataset and its existing feature structure. Additional real-world variables may influence appointment attendance but are not represented in the current data.

## 13.2 Model performance limitations

The retained Logistic Regression model achieved moderate performance on the held-out test set:

Accuracy: 61.50%
Precision: 60.87%
Recall: 69.28%
F1-score: 64.80%
ROC-AUC: 66.47%

These results indicate that the model provides useful predictive information but does not classify appointments with sufficient accuracy to be treated as a definitive prediction system.

The model also produced 216 false positives and 149 false negatives. These errors could result in unnecessary attention being directed towards some patients while other patients at risk of missing appointments are not identified.

## 13.3 Segment performance risk

Model performance is not uniform across all appointment segments.

The most important variation identified during testing occurred across booking lead-time groups. Shorter booking lead-time groups showed relatively low recall, meaning that the model may fail to identify some no-show appointments within these groups.

This finding should therefore remain part of the testing and monitoring requirements for the next stage.

## 13.4 Validation Llimitations

The model demonstrated reasonable stability across the current training/test comparison and 5-fold cross-validation. However, these evaluations were performed using the same project dataset.

The model has not yet been independently validated using a separate external dataset or a temporally separated future dataset. Therefore, the current results do not establish how the model would perform on genuinely unseen future clinic data.

## 13.5 Probability and threshold limitations

The Week 7 testing did not fully evaluate probability calibration or alternative classification thresholds.

The current classification results therefore reflect the existing classification setup and should not be interpreted as demonstrating that the current threshold is optimal for HealthConnect's operational requirements.

Further testing could examine whether different thresholds provide a more appropriate balance between false positives and false negatives.

## 13.6 Operational risk

The model should not be used to make automatic decisions about patients or deny, cancel or restrict healthcare services.

If eventually incorporated into the HealthConnect workflow, its predictions should be treated as decision-support information that can help identify appointments for additional administrative attention.

Any operational implementation would require appropriate human oversight, validation and monitoring.

## 13.7 Interpretation risk

The relationships identified in the dataset are predictive associations and should not be interpreted as evidence that a particular factor causes a patient to miss an appointment.

For example, the relationship between booking lead time and no-show behaviour supports its use as a predictive feature, but does not by itself establish that changing booking lead time would cause attendance behaviour to change.

## 13.8 Cross-track integration risk

The Week 7 cross-track testing demonstrated that the Data Analytics recommendation could be translated into a modelling experiment. However, the tested additive lead_no_show_score did not improve the retained Logistic Regression model.

This demonstrates that an analytical finding can be valid without every proposed modelling representation improving predictive performance.

The result should therefore be treated as evidence for continued investigation rather than as evidence that the underlying Data Analytics findings are invalid.

## 13.9 Overall risk assessment

The main risks remaining at the end of Week 7 are:

1. Moderate overall predictive performance.
2. False-positive and false-negative classification errors.
3. Uneven performance across booking lead-time groups.
4. Lack of independent or temporal external validation.
5. Lack of complete probability calibration and threshold testing.
6. Limitations of the fictional project dataset.
7. The possibility that real-world variables are not represented in the current features.
8. The risk of treating predictive associations as causal relationships.
9. The need for human oversight if the model is eventually integrated into an operational workflow.

These limitations do not prevent the model from continuing to the next development stage, but they should be addressed through further testing and validation before any production deployment is considered.

# 14. Week 8 recommendations

Based on the Week 7 testing, refinement and cross-track validation, the following activities are recommended for Week 8.

## 14.1 Final model candidate

Retain the Week 6 Refined Logistic Regression model as the current candidate model for final integration.

The Week 7 booking lead-time log transformation and the Data Analytics-inspired additive lead_no_show_score were both tested but did not produce meaningful improvements over the retained candidate.

The Week 6 model should therefore remain the reference model for the next stage.

## 14.2 Additional model validation

Where additional data are available, the candidate model should be tested using data that are genuinely independent from the current modelling dataset.

Particular attention should be given to:

* temporally separated data,
* future appointment records,
* performance consistency across different patient and appointment segments, and
* changes in model performance over time.

## 14.3 Threshold and probability testing

Week 8 should investigate whether the current classification threshold is appropriate for the intended HealthConnect use case.

Alternative thresholds can be evaluated to understand their effect on:

* precision,
* recall,
* false positives,
* false negatives, and
* the number of appointments identified for additional attention.

Probability calibration should also be considered before the model is used to support operational decisions.

## 14.4 Focus on booking lead-time segments

Booking lead time should remain a priority area for further testing because it showed the clearest variation in model performance.

Particular attention should be given to the shorter lead-time groups, where recall was relatively low.

The purpose should be to determine whether additional feature refinement, threshold adjustment or other modelling approaches can improve performance without introducing leakage or unnecessary complexity.

## 14.5 Continue monitoring previous no-show history

Previous no-show history should remain an important modelling feature.

The Data Analytics findings showed a consistent relationship between previous no-show history and appointment attendance behaviour. However, very small groups with four or more previous no-shows should be interpreted cautiously because of their limited sample sizes.

## 14.6 Cross-track integration

The Data Science track should continue working with the Data Analytics and Machine Learning Engineering tracks during final integration.

The Data Analytics track can provide validated analytical findings and segment-level evidence, while Data Science can provide the candidate model, evaluation requirements and modelling limitations.

The ML Engineering track can then use the agreed candidate model and interface requirements when integrating the model into the broader HealthConnect workflow.

## 14.7 Final testing evidence

Before the model is considered for any operational implementation, Week 8 should document:

1. Final candidate model.
2. Final feature set.
3. Final evaluation metrics.
4. Confusion matrix and error analysis.
5. Segment-level performance.
6. Threshold and calibration results where applicable.
7. Independent or temporal validation results where available.
8. Cross-track integration evidence.
9. Remaining limitations and risks.
10. Final recommendation regarding the model's readiness for the next stage.

## 14.8 Production readiness

The model should not be presented as production-ready based on the current Week 7 results.

The immediate objective for Week 8 should be final integration, additional validation and evidence-based refinement. A production decision should only be considered after the remaining validation and operational requirements have been addressed.

## 14.9 Overall Week 8 focus

The recommended Week 8 progression is:

Retained candidate → final validation → threshold/calibration testing → cross-track integration → final refinement → documentation → final presentation

This approach maintains continuity with the Week 6 and Week 7 work while ensuring that the final HealthConnect contribution is supported by documented testing evidence rather than performance assumptions.


# 15. Final Week 7 conclusion

Week 7 advanced the HealthConnect Data Science contribution from the Week 6 candidate model into structured testing, refinement, re-testing and cross-track validation.

The Week 6 Refined Logistic Regression model was successfully re-established and tested using the same modelling structure and held-out test set. The model achieved 61.50% accuracy, 60.87% precision, 69.28% recall, 64.80% F1-score and 66.47% ROC-AUC.

Testing identified several important findings. The model showed reasonable stability across the held-out test set, training set and 5-fold cross-validation. However, overall predictive performance remained moderate, and the model continued to produce both false-positive and false-negative classifications.

Segment-level testing showed that booking lead time produced the clearest variation in model performance, particularly among shorter booking lead-time groups. Previous no-show history also remained an important predictive feature. Other tested segments, including appointment type, age, appointment day, appointment time and distance, showed variation but did not provide sufficient evidence to justify independent feature changes.

A targeted Week 7 refinement was therefore conducted by adding a log-transformed representation of booking lead time. The refinement produced almost identical overall performance and did not consistently improve performance across booking lead-time groups. It was consequently rejected and the Week 6 candidate model was retained.

The mandatory cross-track integration with the Data Analytics track was also completed. Validated analytical findings concerning booking lead time and previous no-show history were translated into a modelling experiment using an additive lead_no_show_score. The experiment did not improve model performance, so the proposed representation was not adopted. This provided evidence that the cross-track recommendation had been tested rather than simply documented or communicated.

The Week 7 process therefore resulted in an evidence-based decision to retain the Week 6 Refined Logistic Regression model as the current candidate. Importantly, the absence of a successful metric improvement does not represent a failure of the refinement process. The testing established which proposed changes did not provide sufficient evidence of improvement and prevented unnecessary changes to the candidate model.

The model remains suitable for continued testing and development as a potential decision-support component, but it is not yet production-ready. Further validation should include independent or temporally separated data where available, threshold analysis, probability calibration, continued segment-level evaluation and final integration with the broader HealthConnect solution.

The Week 7 progression can therefore be summarised as:

Week 6 candidate → structured testing → error & segment analysis → targeted refinement → Re-testing → Cross-track validation → Candidate retained → Week 8 Final Integration

Overall, Week 7 demonstrated that the HealthConnect Data Science contribution can be tested, refined and evaluated using evidence-based decisions while maintaining continuity with previous project work. The next stage should focus on final validation, integration and preparation of the model and its supporting evidence for the Week 8 final project stage.
